In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("coag.csv")
df

,NO,Y,Sex 1.Male 2.Female,Age,Before treatment,Severity 1.mild/moderate 2.severe,PT,Platelet,FDP,SIRS_t1,...,SOFA cardiovascular 0-1-2,SOFA CNS,SOFA renal,SOFA renal 0-1-2,Total SOFA (4 items),SIC score (PT+PLT),SIC score（PT+PLT+ Total SOFA）,SIC 1.positive 2.negative,Unnamed: 27,Unnamed: 28
0,1,1,1,72.0,1,2,1.17,41.0,17.00,2,...,2.0,NaN,0,NaN,5,2,4,2,NaN,NaN
1,2,1,2,76.0,1,2,1.95,23.0,18.70,3,...,2.0,3.0,2,2.0,8,4,6,1,NaN,NaN
2,3,2,1,93.0,2,2,1.83,57.0,22.90,3,...,NaN,3.0,0,NaN,2,4,6,1,NaN,NaN
3,4,1,2,76.0,2,2,1.23,66.0,23.40,2,...,2.0,4.0,4,2.0,8,3,5,1,NaN,NaN
4,5,1,1,76.0,2,2,1.08,44.0,3.90,4,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
5,6,2,1,69.0,2,2,1.42,13.0,5.30,3,...,NaN,NaN,0,NaN,0,4,4,2,NaN,NaN
6,7,2,2,63.0,1,2,2.05,53.0,54.50,4,...,2.0,NaN,1,1.0,7,4,6,1,NaN,NaN
7,8,2,1,84.0,2,2,1.19,79.0,5.80,0,...,NaN,0.0,0,NaN,1,2,3,2,NaN,NaN
8,9,1,1,69.0,1,2,1.13,77.0,13.50,3,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
9,10,2,1,63.0,1,2,2.48,31.0,77.80,3,...,2.0,4.0,3,2.0,8,4,6,1,NaN,NaN
10,11,1,1,67.0,1,2,1.61,69.0,23.60,3,...,2.0,1.0,2,2.0,8,4,6,1,NaN,NaN
11,12,1,2,73.0,2,2,1.4,69.0,20.00,2,...,NaN,0.0,0,NaN,0,3,3,2,NaN,NaN
12,13,1,2,71.0,2,1,1.37,70.0,13.00,3,...,NaN,0.0,0,NaN,2,3,5,1,NaN,NaN
13,14,1,2,68.0,2,2,1.63,78.0,27.40,1,...,NaN,1.0,3,2.0,4,4,6,1,NaN,NaN
14,15,1,2,61.0,1,2,1.17,74.0,3.70,2,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
15,16,2,2,84.0,2,2,2.48,38.0,15.80,4,...,2.0,NaN,1,1.0,5,4,6,1,NaN,NaN
16,17,1,1,73.0,2,2,2.27,150.0,40.80,1,...,2.0,4.0,4,2.0,6,2,4,2,NaN,NaN
17,18,1,1,64.0,1,2,1.39,69.0,32.20,3,...,2.0,4.0,3,2.0,8,3,5,1,NaN,NaN
18,19,2,1,34.0,1,2,1.52,40.0,45.40,2,...,2.0,4.0,4,2.0,8,4,6,1,NaN,NaN
19,20,1,1,72.0,1,2,1.37,73.0,19.80,3,...,2.0,0.0,0,NaN,6,3,5,1,NaN,NaN
20,21,1,2,83.0,2,2,1.35,99.0,20.90,2,...,2.0,1.0,0,NaN,4,3,5,1,NaN,NaN
21,22,1,2,77.0,2,2,1.42,80.0,180.00,3,...,2.0,0.0,2,2.0,6,4,6,1,NaN,NaN
22,23,1,2,63.0,2,2,1.71,37.0,20.90,4,...,2.0,1.0,0,NaN,4,4,6,1,NaN,NaN
23,24,2,1,36.0,1,2,1.51,65.0,5.00,4,...,NaN,3.0,0,NaN,1,4,5,1,NaN,NaN
24,25,1,1,70.0,2,2,1.15,22.0,103.00,3,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
25,26,1,1,78.0,2,2,1.21,49.0,62.30,2,...,2.0,2.0,2,2.0,6,3,5,1,NaN,NaN
26,27,2,1,68.0,2,2,1.1,55.0,28.00,3,...,2.0,1.0,4,2.0,6,2,4,2,NaN,NaN
27,28,2,2,87.0,2,2,1.39,74.0,10.20,2,...,2.0,4.0,1,1.0,5,3,5,1,NaN,NaN
28,29,1,1,66.0,1,2,1.31,12.0,11.00,3,...,1.0,1.0,0,NaN,5,3,5,1,NaN,NaN
29,30,1,2,19.0,1,2,1.53,48.0,140.80,4,...,2.0,NaN,0,NaN,4,4,6,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1469,1,1,83.0,2,2,1.87,56.0,15.30,4,...,2.0,0.0,0,NaN,5,4,6,1,NaN,NaN
1469,1470,1,1,87.0,2,2,1.49,135.0,34.00,2,...,2.0,0.0,0,NaN,2,3,5,1,NaN,NaN
1470,1471,2,2,88.0,2,2,1.55,65.0,19.80,3,...,2.0,1.0,0,NaN,5,4,6,1,NaN,NaN
1471,1472,1,1,69.0,2,2,1.17,106.0,NaN,3,...,2.0,0.0,0,NaN,5,1,3,2,NaN,NaN
1472,1473,2,2,65.0,1,2,1.45,7.0,33.20,0,...,2.0,0.0,4,2.0,8,4,6,1,NaN,NaN
1473,1474,2,1,69.0,2,2,3.26,27.0,15.60,4,...,2.0,NaN,2,2.0,8,4,6,1,NaN,NaN
1474,1475,2,2,73.0,1,2,1.41,48.0,20.70,2,...,2.0,4.0,0,NaN,3,4,6,1,NaN,NaN
1475,1476,1,1,93.0,2,2,1.39,40.0,23.70,3,...,1.0,NaN,2,2.0,7,3,5,1,NaN,NaN
1476,1477,2,1,81.0,2,2,1.49,32.0,31.60,3,...,NaN,1.0,1,1.0,3,4,6,1,NaN,NaN
1477,1478,1,1,47.0,2,2,1.42,80.0,12.40,3,...,1.0,NaN,0,NaN,2,4,6,1,NaN,NaN
1478,1479,1,1,75.0,2,1,1.06,30.0,10.50,2,...,NaN,0.0,0,NaN,2,2,4,2,NaN,NaN
1479,1480,1,2,89.0,2,2,3.09,227.0,80.00,4,...,NaN,3.0,1,1.0,2,2,4,2,NaN,NaN
1480,1481,2,1,86.0,2,2,1.42,57.0,NaN,2,...,2.0,4.0,0,NaN,4,4,6,1,NaN,NaN
1481,1482,1,2,83.0,2,1,1.2,30.0,8.00,3,...,1.0,3.0,0,NaN,1,2,3,2,NaN,NaN
1482,1483,2,1,67.0,2,2,1.08,65.0,19.20,2,...,2.0,4.0,3,2.0,6,2,4,2,NaN,NaN
1483,1484,1,1,NaN,1,2,1.34,40.0,8.30,3,...,NaN,NaN,0,NaN,2,3,5,1,NaN,NaN
1484,1485,2,1,76.0,2,2,1.33,21.0,5.00,4,...,2.0,4.0,0,NaN,6,3,5,1,NaN,NaN
1485,1486,1,2,76.0,1,2,1.5,92.0,7.86,3,...,1.0,0.0,0,NaN,2,4,6,1,NaN,NaN
1486,1487,1,2,42.0,1,2,1.3,96.0,NaN,4,...,1.0,NaN,0,NaN,3,3,5,1,NaN,NaN
1487,1488,1,2,65.0,2,2,1.37,51.0,45.90,3,...,NaN,NaN,1,1.0,2,3,5,1,NaN,NaN
1488,1489,2,1,88.0,2,2,1.23,64.0,14.02,2,...,NaN,NaN,1,1.0,3,3,5,1,NaN,NaN
1489,1490,2,2,74.0,1,2,1.45,89.0,91.90,4,...,2.0,4.0,3,2.0,6,4,6,1,NaN,NaN
1490,1491,1,1,6.0,2,2,1.95,26.0,NaN,4,...,2.0,NaN,2,2.0,6,4,6,1,NaN,NaN
1491,1492,1,1,60.0,2,2,1.39,33.0,73.50,1,...,2.0,0.0,0,NaN,5,3,5,1,NaN,NaN
1492,1493,1,2,58.0,2,2,1.23,105.0,19.00,2,...,2.0,0.0,4,2.0,5,2,4,2,NaN,NaN
1493,1494,2,1,84.0,2,2,1.21,40.0,49.40,2,...,2.0,4.0,0,NaN,5,3,5,1,NaN,NaN
1494,1495,1,1,4.0,2,2,2.86,283.0,586.20,2,...,2.0,3.0,0,NaN,4,2,4,2,NaN,NaN
1495,1496,1,1,65.0,1,2,1.02,28.0,71.00,3,...,2.0,1.0,1,1.0,6,2,4,2,NaN,NaN
1496,1497,2,1,80.0,1,2,1.46,55.0,15.10,1,...,2.0,NaN,4,2.0,6,4,6,1,NaN,NaN
1497,1498,2,1,82.0,1,2,1.94,25.0,37.10,4,...,2.0,2.0,1,1.0,7,4,6,1,NaN,NaN

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1498 entries, 0 to 1497
Data columns (total 29 columns):
NO                                        1498 non-null int64
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
PT                                        1498 non-null object
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
respiratory
0-1-2                    1262 non-null float64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
hepatic
0-1-2                        783 non-null float64
SOFA
cardiovascular                       1498 non-null int64
SOFA
cardiovascular
0-1-2                 1128 non-null float64
SOFA
CNS                                  1160 non-null float64
SOFA
renal                                1498 non-null int64
SOFA
renal
0-1-2                          894 non-null float64
Total SOFA
(4 items)                      1498 non-null int64
SIC score
(PT+PLT)                        1498 non-null int64
SIC score（PT+PLT+
 Total SOFA）            1498 non-null int64
SIC
1.positive
2.negative                 1498 non-null int64
Unnamed: 27                               0 non-null float64
Unnamed: 28                               0 non-null float64
dtypes: float64(10), int64(18), object(1)
memory usage: 339.5+ KB

In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

,NO,Y,Sex 1.Male 2.Female,Age,Before treatment,Severity 1.mild/moderate 2.severe,PT,Platelet,FDP,SIRS_t1,...,SOFA cardiovascular 0-1-2,SOFA CNS,SOFA renal,SOFA renal 0-1-2,Total SOFA (4 items),SIC score (PT+PLT),SIC score（PT+PLT+ Total SOFA）,SIC 1.positive 2.negative,Unnamed: 27,Unnamed: 28
0,1,1,1,72.0,1,2,1.17,41.0,17.00,2,...,2.0,NaN,0,NaN,5,2,4,2,NaN,NaN
1,2,1,2,76.0,1,2,1.95,23.0,18.70,3,...,2.0,3.0,2,2.0,8,4,6,1,NaN,NaN
2,3,2,1,93.0,2,2,1.83,57.0,22.90,3,...,NaN,3.0,0,NaN,2,4,6,1,NaN,NaN
3,4,1,2,76.0,2,2,1.23,66.0,23.40,2,...,2.0,4.0,4,2.0,8,3,5,1,NaN,NaN
4,5,1,1,76.0,2,2,1.08,44.0,3.90,4,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
5,6,2,1,69.0,2,2,1.42,13.0,5.30,3,...,NaN,NaN,0,NaN,0,4,4,2,NaN,NaN
6,7,2,2,63.0,1,2,2.05,53.0,54.50,4,...,2.0,NaN,1,1.0,7,4,6,1,NaN,NaN
7,8,2,1,84.0,2,2,1.19,79.0,5.80,0,...,NaN,0.0,0,NaN,1,2,3,2,NaN,NaN
8,9,1,1,69.0,1,2,1.13,77.0,13.50,3,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
9,10,2,1,63.0,1,2,2.48,31.0,77.80,3,...,2.0,4.0,3,2.0,8,4,6,1,NaN,NaN
10,11,1,1,67.0,1,2,1.61,69.0,23.60,3,...,2.0,1.0,2,2.0,8,4,6,1,NaN,NaN
11,12,1,2,73.0,2,2,1.4,69.0,20.00,2,...,NaN,0.0,0,NaN,0,3,3,2,NaN,NaN
12,13,1,2,71.0,2,1,1.37,70.0,13.00,3,...,NaN,0.0,0,NaN,2,3,5,1,NaN,NaN
13,14,1,2,68.0,2,2,1.63,78.0,27.40,1,...,NaN,1.0,3,2.0,4,4,6,1,NaN,NaN
14,15,1,2,61.0,1,2,1.17,74.0,3.70,2,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
15,16,2,2,84.0,2,2,2.48,38.0,15.80,4,...,2.0,NaN,1,1.0,5,4,6,1,NaN,NaN
16,17,1,1,73.0,2,2,2.27,150.0,40.80,1,...,2.0,4.0,4,2.0,6,2,4,2,NaN,NaN
17,18,1,1,64.0,1,2,1.39,69.0,32.20,3,...,2.0,4.0,3,2.0,8,3,5,1,NaN,NaN
18,19,2,1,34.0,1,2,1.52,40.0,45.40,2,...,2.0,4.0,4,2.0,8,4,6,1,NaN,NaN
19,20,1,1,72.0,1,2,1.37,73.0,19.80,3,...,2.0,0.0,0,NaN,6,3,5,1,NaN,NaN
20,21,1,2,83.0,2,2,1.35,99.0,20.90,2,...,2.0,1.0,0,NaN,4,3,5,1,NaN,NaN
21,22,1,2,77.0,2,2,1.42,80.0,180.00,3,...,2.0,0.0,2,2.0,6,4,6,1,NaN,NaN
22,23,1,2,63.0,2,2,1.71,37.0,20.90,4,...,2.0,1.0,0,NaN,4,4,6,1,NaN,NaN
23,24,2,1,36.0,1,2,1.51,65.0,5.00,4,...,NaN,3.0,0,NaN,1,4,5,1,NaN,NaN
24,25,1,1,70.0,2,2,1.15,22.0,103.00,3,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
25,26,1,1,78.0,2,2,1.21,49.0,62.30,2,...,2.0,2.0,2,2.0,6,3,5,1,NaN,NaN
26,27,2,1,68.0,2,2,1.1,55.0,28.00,3,...,2.0,1.0,4,2.0,6,2,4,2,NaN,NaN
27,28,2,2,87.0,2,2,1.39,74.0,10.20,2,...,2.0,4.0,1,1.0,5,3,5,1,NaN,NaN
28,29,1,1,66.0,1,2,1.31,12.0,11.00,3,...,1.0,1.0,0,NaN,5,3,5,1,NaN,NaN
29,30,1,2,19.0,1,2,1.53,48.0,140.80,4,...,2.0,NaN,0,NaN,4,4,6,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1469,1,1,83.0,2,2,1.87,56.0,15.30,4,...,2.0,0.0,0,NaN,5,4,6,1,NaN,NaN
1469,1470,1,1,87.0,2,2,1.49,135.0,34.00,2,...,2.0,0.0,0,NaN,2,3,5,1,NaN,NaN
1470,1471,2,2,88.0,2,2,1.55,65.0,19.80,3,...,2.0,1.0,0,NaN,5,4,6,1,NaN,NaN
1471,1472,1,1,69.0,2,2,1.17,106.0,NaN,3,...,2.0,0.0,0,NaN,5,1,3,2,NaN,NaN
1472,1473,2,2,65.0,1,2,1.45,7.0,33.20,0,...,2.0,0.0,4,2.0,8,4,6,1,NaN,NaN
1473,1474,2,1,69.0,2,2,3.26,27.0,15.60,4,...,2.0,NaN,2,2.0,8,4,6,1,NaN,NaN
1474,1475,2,2,73.0,1,2,1.41,48.0,20.70,2,...,2.0,4.0,0,NaN,3,4,6,1,NaN,NaN
1475,1476,1,1,93.0,2,2,1.39,40.0,23.70,3,...,1.0,NaN,2,2.0,7,3,5,1,NaN,NaN
1476,1477,2,1,81.0,2,2,1.49,32.0,31.60,3,...,NaN,1.0,1,1.0,3,4,6,1,NaN,NaN
1477,1478,1,1,47.0,2,2,1.42,80.0,12.40,3,...,1.0,NaN,0,NaN,2,4,6,1,NaN,NaN
1478,1479,1,1,75.0,2,1,1.06,30.0,10.50,2,...,NaN,0.0,0,NaN,2,2,4,2,NaN,NaN
1479,1480,1,2,89.0,2,2,3.09,227.0,80.00,4,...,NaN,3.0,1,1.0,2,2,4,2,NaN,NaN
1480,1481,2,1,86.0,2,2,1.42,57.0,NaN,2,...,2.0,4.0,0,NaN,4,4,6,1,NaN,NaN
1481,1482,1,2,83.0,2,1,1.2,30.0,8.00,3,...,1.0,3.0,0,NaN,1,2,3,2,NaN,NaN
1482,1483,2,1,67.0,2,2,1.08,65.0,19.20,2,...,2.0,4.0,3,2.0,6,2,4,2,NaN,NaN
1483,1484,1,1,NaN,1,2,1.34,40.0,8.30,3,...,NaN,NaN,0,NaN,2,3,5,1,NaN,NaN
1484,1485,2,1,76.0,2,2,1.33,21.0,5.00,4,...,2.0,4.0,0,NaN,6,3,5,1,NaN,NaN
1485,1486,1,2,76.0,1,2,1.5,92.0,7.86,3,...,1.0,0.0,0,NaN,2,4,6,1,NaN,NaN
1486,1487,1,2,42.0,1,2,1.3,96.0,NaN,4,...,1.0,NaN,0,NaN,3,3,5,1,NaN,NaN
1487,1488,1,2,65.0,2,2,1.37,51.0,45.90,3,...,NaN,NaN,1,1.0,2,3,5,1,NaN,NaN
1488,1489,2,1,88.0,2,2,1.23,64.0,14.02,2,...,NaN,NaN,1,1.0,3,3,5,1,NaN,NaN
1489,1490,2,2,74.0,1,2,1.45,89.0,91.90,4,...,2.0,4.0,3,2.0,6,4,6,1,NaN,NaN
1490,1491,1,1,6.0,2,2,1.95,26.0,NaN,4,...,2.0,NaN,2,2.0,6,4,6,1,NaN,NaN
1491,1492,1,1,60.0,2,2,1.39,33.0,73.50,1,...,2.0,0.0,0,NaN,5,3,5,1,NaN,NaN
1492,1493,1,2,58.0,2,2,1.23,105.0,19.00,2,...,2.0,0.0,4,2.0,5,2,4,2,NaN,NaN
1493,1494,2,1,84.0,2,2,1.21,40.0,49.40,2,...,2.0,4.0,0,NaN,5,3,5,1,NaN,NaN
1494,1495,1,1,4.0,2,2,2.86,283.0,586.20,2,...,2.0,3.0,0,NaN,4,2,4,2,NaN,NaN
1495,1496,1,1,65.0,1,2,1.02,28.0,71.00,3,...,2.0,1.0,1,1.0,6,2,4,2,NaN,NaN
1496,1497,2,1,80.0,1,2,1.46,55.0,15.10,1,...,2.0,NaN,4,2.0,6,4,6,1,NaN,NaN
1497,1498,2,1,82.0,1,2,1.94,25.0,37.10,4,...,2.0,2.0,1,1.0,7,4,6,1,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1498 entries, 0 to 1497
Data columns (total 29 columns):
NO                                        1498 non-null int64
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
PT                                        1498 non-null object
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
respiratory
0-1-2                    1262 non-null float64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
hepatic
0-1-2                        783 non-null float64
SOFA
cardiovascular                       1498 non-null int64
SOFA
cardiovascular
0-1-2                 1128 non-null float64
SOFA
CNS                                  1160 non-null float64
SOFA
renal                                1498 non-null int64
SOFA
renal
0-1-2                          894 non-null float64
Total SOFA
(4 items)                      1498 non-null int64
SIC score
(PT+PLT)                        1498 non-null int64
SIC score（PT+PLT+
 Total SOFA）            1498 non-null int64
SIC
1.positive
2.negative                 1498 non-null int64
Unnamed: 27                               0 non-null float64
Unnamed: 28                               0 non-null float64
dtypes: float64(10), int64(18), object(1)
memory usage: 339.5+ KB

In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

## Data Cleaning

In [8]:
# Drop the column `ID` as it is unrelated to the dependent variable
df = df.drop(['NO','PT'],axis=1)
df

,Y,Sex 1.Male 2.Female,Age,Before treatment,Severity 1.mild/moderate 2.severe,Platelet,FDP,SIRS_t1,SIRS 3 or more 1. positive 2. negative,JAAM DIC score,...,SOFA cardiovascular 0-1-2,SOFA CNS,SOFA renal,SOFA renal 0-1-2,Total SOFA (4 items),SIC score (PT+PLT),SIC score（PT+PLT+ Total SOFA）,SIC 1.positive 2.negative,Unnamed: 27,Unnamed: 28
0,1,1,72.0,1,2,41.0,17.00,2,2,4,...,2.0,NaN,0,NaN,5,2,4,2,NaN,NaN
1,1,2,76.0,1,2,23.0,18.70,3,1,6,...,2.0,3.0,2,2.0,8,4,6,1,NaN,NaN
2,2,1,93.0,2,2,57.0,22.90,3,1,6,...,NaN,3.0,0,NaN,2,4,6,1,NaN,NaN
3,1,2,76.0,2,2,66.0,23.40,2,2,5,...,2.0,4.0,4,2.0,8,3,5,1,NaN,NaN
4,1,1,76.0,2,2,44.0,3.90,4,1,4,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
5,2,1,69.0,2,2,13.0,5.30,3,1,5,...,NaN,NaN,0,NaN,0,4,4,2,NaN,NaN
6,2,2,63.0,1,2,53.0,54.50,4,1,8,...,2.0,NaN,1,1.0,7,4,6,1,NaN,NaN
7,2,1,84.0,2,2,79.0,5.80,0,2,3,...,NaN,0.0,0,NaN,1,2,3,2,NaN,NaN
8,1,1,69.0,1,2,77.0,13.50,3,1,5,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
9,2,1,63.0,1,2,31.0,77.80,3,1,8,...,2.0,4.0,3,2.0,8,4,6,1,NaN,NaN
10,1,1,67.0,1,2,69.0,23.60,3,1,6,...,2.0,1.0,2,2.0,8,4,6,1,NaN,NaN
11,1,2,73.0,2,2,69.0,20.00,2,2,5,...,NaN,0.0,0,NaN,0,3,3,2,NaN,NaN
12,1,2,71.0,2,1,70.0,13.00,3,1,6,...,NaN,0.0,0,NaN,2,3,5,1,NaN,NaN
13,1,2,68.0,2,2,78.0,27.40,1,2,7,...,NaN,1.0,3,2.0,4,4,6,1,NaN,NaN
14,1,2,61.0,1,2,74.0,3.70,2,2,3,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
15,2,2,84.0,2,2,38.0,15.80,4,1,6,...,2.0,NaN,1,1.0,5,4,6,1,NaN,NaN
16,1,1,73.0,2,2,150.0,40.80,1,2,4,...,2.0,4.0,4,2.0,6,2,4,2,NaN,NaN
17,1,1,64.0,1,2,69.0,32.20,3,1,8,...,2.0,4.0,3,2.0,8,3,5,1,NaN,NaN
18,2,1,34.0,1,2,40.0,45.40,2,2,7,...,2.0,4.0,4,2.0,8,4,6,1,NaN,NaN
19,1,1,72.0,1,2,73.0,19.80,3,1,6,...,2.0,0.0,0,NaN,6,3,5,1,NaN,NaN
20,1,2,83.0,2,2,99.0,20.90,2,2,3,...,2.0,1.0,0,NaN,4,3,5,1,NaN,NaN
21,1,2,77.0,2,2,80.0,180.00,3,1,6,...,2.0,0.0,2,2.0,6,4,6,1,NaN,NaN
22,1,2,63.0,2,2,37.0,20.90,4,1,6,...,2.0,1.0,0,NaN,4,4,6,1,NaN,NaN
23,2,1,36.0,1,2,65.0,5.00,4,1,5,...,NaN,3.0,0,NaN,1,4,5,1,NaN,NaN
24,1,1,70.0,2,2,22.0,103.00,3,1,7,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
25,1,1,78.0,2,2,49.0,62.30,2,2,7,...,2.0,2.0,2,2.0,6,3,5,1,NaN,NaN
26,2,1,68.0,2,2,55.0,28.00,3,1,7,...,2.0,1.0,4,2.0,6,2,4,2,NaN,NaN
27,2,2,87.0,2,2,74.0,10.20,2,2,5,...,2.0,4.0,1,1.0,5,3,5,1,NaN,NaN
28,1,1,66.0,1,2,12.0,11.00,3,1,6,...,1.0,1.0,0,NaN,5,3,5,1,NaN,NaN
29,1,2,19.0,1,2,48.0,140.80,4,1,8,...,2.0,NaN,0,NaN,4,4,6,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1,1,83.0,2,2,56.0,15.30,4,1,6,...,2.0,0.0,0,NaN,5,4,6,1,NaN,NaN
1469,1,1,87.0,2,2,135.0,34.00,2,2,4,...,2.0,0.0,0,NaN,2,3,5,1,NaN,NaN
1470,2,2,88.0,2,2,65.0,19.80,3,1,6,...,2.0,1.0,0,NaN,5,4,6,1,NaN,NaN
1471,1,1,69.0,2,2,106.0,NaN,3,1,3,...,2.0,0.0,0,NaN,5,1,3,2,NaN,NaN
1472,2,2,65.0,1,2,7.0,33.20,0,2,7,...,2.0,0.0,4,2.0,8,4,6,1,NaN,NaN
1473,2,1,69.0,2,2,27.0,15.60,4,1,6,...,2.0,NaN,2,2.0,8,4,6,1,NaN,NaN
1474,2,2,73.0,1,2,48.0,20.70,2,2,5,...,2.0,4.0,0,NaN,3,4,6,1,NaN,NaN
1475,1,1,93.0,2,2,40.0,23.70,3,1,6,...,1.0,NaN,2,2.0,7,3,5,1,NaN,NaN
1476,2,1,81.0,2,2,32.0,31.60,3,1,8,...,NaN,1.0,1,1.0,3,4,6,1,NaN,NaN
1477,1,1,47.0,2,2,80.0,12.40,3,1,4,...,1.0,NaN,0,NaN,2,4,6,1,NaN,NaN
1478,1,1,75.0,2,1,30.0,10.50,2,2,4,...,NaN,0.0,0,NaN,2,2,4,2,NaN,NaN
1479,1,2,89.0,2,2,227.0,80.00,4,1,5,...,NaN,3.0,1,1.0,2,2,4,2,NaN,NaN
1480,2,1,86.0,2,2,57.0,NaN,2,2,4,...,2.0,4.0,0,NaN,4,4,6,1,NaN,NaN
1481,1,2,83.0,2,1,30.0,8.00,3,1,5,...,1.0,3.0,0,NaN,1,2,3,2,NaN,NaN
1482,2,1,67.0,2,2,65.0,19.20,2,2,4,...,2.0,4.0,3,2.0,6,2,4,2,NaN,NaN
1483,1,1,NaN,1,2,40.0,8.30,3,1,5,...,NaN,NaN,0,NaN,2,3,5,1,NaN,NaN
1484,2,1,76.0,2,2,21.0,5.00,4,1,5,...,2.0,4.0,0,NaN,6,3,5,1,NaN,NaN
1485,1,2,76.0,1,2,92.0,7.86,3,1,3,...,1.0,0.0,0,NaN,2,4,6,1,NaN,NaN
1486,1,2,42.0,1,2,96.0,NaN,4,1,4,...,1.0,NaN,0,NaN,3,3,5,1,NaN,NaN
1487,1,2,65.0,2,2,51.0,45.90,3,1,8,...,NaN,NaN,1,1.0,2,3,5,1,NaN,NaN
1488,2,1,88.0,2,2,64.0,14.02,2,2,5,...,NaN,NaN,1,1.0,3,3,5,1,NaN,NaN
1489,2,2,74.0,1,2,89.0,91.90,4,1,6,...,2.0,4.0,3,2.0,6,4,6,1,NaN,NaN
1490,1,1,6.0,2,2,26.0,NaN,4,1,8,...,2.0,NaN,2,2.0,6,4,6,1,NaN,NaN
1491,1,1,60.0,2,2,33.0,73.50,1,2,7,...,2.0,0.0,0,NaN,5,3,5,1,NaN,NaN
1492,1,2,58.0,2,2,105.0,19.00,2,2,3,...,2.0,0.0,4,2.0,5,2,4,2,NaN,NaN
1493,2,1,84.0,2,2,40.0,49.40,2,2,7,...,2.0,4.0,0,NaN,5,3,5,1,NaN,NaN
1494,1,1,4.0,2,2,283.0,586.20,2,2,4,...,2.0,3.0,0,NaN,4,2,4,2,NaN,NaN
1495,1,1,65.0,1,2,28.0,71.00,3,1,7,...,2.0,1.0,1,1.0,6,2,4,2,NaN,NaN
1496,2,1,80.0,1,2,55.0,15.10,1,2,5,...,2.0,NaN,4,2.0,6,4,6,1,NaN,NaN
1497,2,1,82.0,1,2,25.0,37.10,4,1,8,...,2.0,2.0,1,1.0,7,4,6,1,NaN,NaN

In [9]:
# Remove rows where taget are missing
missing_row = df['Y'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0

,Y,Sex 1.Male 2.Female,Age,Before treatment,Severity 1.mild/moderate 2.severe,Platelet,FDP,SIRS_t1,SIRS 3 or more 1. positive 2. negative,JAAM DIC score,...,SOFA cardiovascular 0-1-2,SOFA CNS,SOFA renal,SOFA renal 0-1-2,Total SOFA (4 items),SIC score (PT+PLT),SIC score（PT+PLT+ Total SOFA）,SIC 1.positive 2.negative,Unnamed: 27,Unnamed: 28
0,1,1,72.0,1,2,41.0,17.00,2,2,4,...,2.0,NaN,0,NaN,5,2,4,2,NaN,NaN
1,1,2,76.0,1,2,23.0,18.70,3,1,6,...,2.0,3.0,2,2.0,8,4,6,1,NaN,NaN
2,2,1,93.0,2,2,57.0,22.90,3,1,6,...,NaN,3.0,0,NaN,2,4,6,1,NaN,NaN
3,1,2,76.0,2,2,66.0,23.40,2,2,5,...,2.0,4.0,4,2.0,8,3,5,1,NaN,NaN
4,1,1,76.0,2,2,44.0,3.90,4,1,4,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
5,2,1,69.0,2,2,13.0,5.30,3,1,5,...,NaN,NaN,0,NaN,0,4,4,2,NaN,NaN
6,2,2,63.0,1,2,53.0,54.50,4,1,8,...,2.0,NaN,1,1.0,7,4,6,1,NaN,NaN
7,2,1,84.0,2,2,79.0,5.80,0,2,3,...,NaN,0.0,0,NaN,1,2,3,2,NaN,NaN
8,1,1,69.0,1,2,77.0,13.50,3,1,5,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
9,2,1,63.0,1,2,31.0,77.80,3,1,8,...,2.0,4.0,3,2.0,8,4,6,1,NaN,NaN
10,1,1,67.0,1,2,69.0,23.60,3,1,6,...,2.0,1.0,2,2.0,8,4,6,1,NaN,NaN
11,1,2,73.0,2,2,69.0,20.00,2,2,5,...,NaN,0.0,0,NaN,0,3,3,2,NaN,NaN
12,1,2,71.0,2,1,70.0,13.00,3,1,6,...,NaN,0.0,0,NaN,2,3,5,1,NaN,NaN
13,1,2,68.0,2,2,78.0,27.40,1,2,7,...,NaN,1.0,3,2.0,4,4,6,1,NaN,NaN
14,1,2,61.0,1,2,74.0,3.70,2,2,3,...,1.0,2.0,3,2.0,3,2,4,2,NaN,NaN
15,2,2,84.0,2,2,38.0,15.80,4,1,6,...,2.0,NaN,1,1.0,5,4,6,1,NaN,NaN
16,1,1,73.0,2,2,150.0,40.80,1,2,4,...,2.0,4.0,4,2.0,6,2,4,2,NaN,NaN
17,1,1,64.0,1,2,69.0,32.20,3,1,8,...,2.0,4.0,3,2.0,8,3,5,1,NaN,NaN
18,2,1,34.0,1,2,40.0,45.40,2,2,7,...,2.0,4.0,4,2.0,8,4,6,1,NaN,NaN
19,1,1,72.0,1,2,73.0,19.80,3,1,6,...,2.0,0.0,0,NaN,6,3,5,1,NaN,NaN
20,1,2,83.0,2,2,99.0,20.90,2,2,3,...,2.0,1.0,0,NaN,4,3,5,1,NaN,NaN
21,1,2,77.0,2,2,80.0,180.00,3,1,6,...,2.0,0.0,2,2.0,6,4,6,1,NaN,NaN
22,1,2,63.0,2,2,37.0,20.90,4,1,6,...,2.0,1.0,0,NaN,4,4,6,1,NaN,NaN
23,2,1,36.0,1,2,65.0,5.00,4,1,5,...,NaN,3.0,0,NaN,1,4,5,1,NaN,NaN
24,1,1,70.0,2,2,22.0,103.00,3,1,7,...,NaN,0.0,1,1.0,3,2,4,2,NaN,NaN
25,1,1,78.0,2,2,49.0,62.30,2,2,7,...,2.0,2.0,2,2.0,6,3,5,1,NaN,NaN
26,2,1,68.0,2,2,55.0,28.00,3,1,7,...,2.0,1.0,4,2.0,6,2,4,2,NaN,NaN
27,2,2,87.0,2,2,74.0,10.20,2,2,5,...,2.0,4.0,1,1.0,5,3,5,1,NaN,NaN
28,1,1,66.0,1,2,12.0,11.00,3,1,6,...,1.0,1.0,0,NaN,5,3,5,1,NaN,NaN
29,1,2,19.0,1,2,48.0,140.80,4,1,8,...,2.0,NaN,0,NaN,4,4,6,1,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1,1,83.0,2,2,56.0,15.30,4,1,6,...,2.0,0.0,0,NaN,5,4,6,1,NaN,NaN
1469,1,1,87.0,2,2,135.0,34.00,2,2,4,...,2.0,0.0,0,NaN,2,3,5,1,NaN,NaN
1470,2,2,88.0,2,2,65.0,19.80,3,1,6,...,2.0,1.0,0,NaN,5,4,6,1,NaN,NaN
1471,1,1,69.0,2,2,106.0,NaN,3,1,3,...,2.0,0.0,0,NaN,5,1,3,2,NaN,NaN
1472,2,2,65.0,1,2,7.0,33.20,0,2,7,...,2.0,0.0,4,2.0,8,4,6,1,NaN,NaN
1473,2,1,69.0,2,2,27.0,15.60,4,1,6,...,2.0,NaN,2,2.0,8,4,6,1,NaN,NaN
1474,2,2,73.0,1,2,48.0,20.70,2,2,5,...,2.0,4.0,0,NaN,3,4,6,1,NaN,NaN
1475,1,1,93.0,2,2,40.0,23.70,3,1,6,...,1.0,NaN,2,2.0,7,3,5,1,NaN,NaN
1476,2,1,81.0,2,2,32.0,31.60,3,1,8,...,NaN,1.0,1,1.0,3,4,6,1,NaN,NaN
1477,1,1,47.0,2,2,80.0,12.40,3,1,4,...,1.0,NaN,0,NaN,2,4,6,1,NaN,NaN
1478,1,1,75.0,2,1,30.0,10.50,2,2,4,...,NaN,0.0,0,NaN,2,2,4,2,NaN,NaN
1479,1,2,89.0,2,2,227.0,80.00,4,1,5,...,NaN,3.0,1,1.0,2,2,4,2,NaN,NaN
1480,2,1,86.0,2,2,57.0,NaN,2,2,4,...,2.0,4.0,0,NaN,4,4,6,1,NaN,NaN
1481,1,2,83.0,2,1,30.0,8.00,3,1,5,...,1.0,3.0,0,NaN,1,2,3,2,NaN,NaN
1482,2,1,67.0,2,2,65.0,19.20,2,2,4,...,2.0,4.0,3,2.0,6,2,4,2,NaN,NaN
1483,1,1,NaN,1,2,40.0,8.30,3,1,5,...,NaN,NaN,0,NaN,2,3,5,1,NaN,NaN
1484,2,1,76.0,2,2,21.0,5.00,4,1,5,...,2.0,4.0,0,NaN,6,3,5,1,NaN,NaN
1485,1,2,76.0,1,2,92.0,7.86,3,1,3,...,1.0,0.0,0,NaN,2,4,6,1,NaN,NaN
1486,1,2,42.0,1,2,96.0,NaN,4,1,4,...,1.0,NaN,0,NaN,3,3,5,1,NaN,NaN
1487,1,2,65.0,2,2,51.0,45.90,3,1,8,...,NaN,NaN,1,1.0,2,3,5,1,NaN,NaN
1488,2,1,88.0,2,2,64.0,14.02,2,2,5,...,NaN,NaN,1,1.0,3,3,5,1,NaN,NaN
1489,2,2,74.0,1,2,89.0,91.90,4,1,6,...,2.0,4.0,3,2.0,6,4,6,1,NaN,NaN
1490,1,1,6.0,2,2,26.0,NaN,4,1,8,...,2.0,NaN,2,2.0,6,4,6,1,NaN,NaN
1491,1,1,60.0,2,2,33.0,73.50,1,2,7,...,2.0,0.0,0,NaN,5,3,5,1,NaN,NaN
1492,1,2,58.0,2,2,105.0,19.00,2,2,3,...,2.0,0.0,4,2.0,5,2,4,2,NaN,NaN
1493,2,1,84.0,2,2,40.0,49.40,2,2,7,...,2.0,4.0,0,NaN,5,3,5,1,NaN,NaN
1494,1,1,4.0,2,2,283.0,586.20,2,2,4,...,2.0,3.0,0,NaN,4,2,4,2,NaN,NaN
1495,1,1,65.0,1,2,28.0,71.00,3,1,7,...,2.0,1.0,1,1.0,6,2,4,2,NaN,NaN
1496,2,1,80.0,1,2,55.0,15.10,1,2,5,...,2.0,NaN,4,2.0,6,4,6,1,NaN,NaN
1497,2,1,82.0,1,2,25.0,37.10,4,1,8,...,2.0,2.0,1,1.0,7,4,6,1,NaN,NaN

We determine and drop the variables with excessive missing values from the dataset.

In [10]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df

In [11]:
df = remove_bad_columns(df,200)
df.info()

number of bad columns: 7
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 20 columns):
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
cardiovascular                       1498 non-null int64
SOFA
renal                                1498 non-null int64
Total SOFA
(4 items)                      1498 non-null int64
SIC score
(PT+PLT)                        1498 non-null int64
SIC score（PT+PLT+
 Total SOFA）            1498 non-null int64
SIC
1.positive
2.negative                 1498 non-null int64
dtypes: float64(3), int64(17)
memory usage: 245.8 KB

We find bad rows which contain too many missing values, then remove them.

In [12]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [13]:
df = remove_bad_rows(df,5)
df.info()

number of bad rows: 0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 20 columns):
Y                                         1498 non-null int64
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1494 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1303 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
cardiovascular                       1498 non-null int64
SOFA
renal                                1498 non-null int64
Total SOFA
(4 items)                      1498 non-null int64
SIC score
(PT+PLT)                        1498 non-null int64
SIC score（PT+PLT+
 Total SOFA）            1498 non-null int64
SIC
1.positive
2.negative                 1498 non-null int64
dtypes: float64(3), int64(17)
memory usage: 245.8 KB

For convenience, we separate independents `X` and dependent `y` from the data.

In [14]:
dfx = df.drop('Y',axis=1)
dfy = df['Y']

In [15]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[  2  97   2   2 236 688   5   2   9   2   5   5   5   5   5   9   5   7
   2]

In [16]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [17]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [0, 2, 3, 7, 9, 18]
i_category: []
variable type: [1. 3. 1. 1. 3. 3. 3. 1. 3. 1. 3. 3. 3. 3. 3. 3. 3. 3. 1.]

In [18]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2

In [19]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

,Sex 1.Male 2.Female,Age,Before treatment,Severity 1.mild/moderate 2.severe,Platelet,FDP,SIRS_t1,SIRS 3 or more 1. positive 2. negative,JAAM DIC score,JAAM DIC 1.positive 2.negative,SOFA respiratory,SOFA coagulation,SOFA hepatic,SOFA cardiovascular,SOFA renal,Total SOFA (4 items),SIC score (PT+PLT),SIC score（PT+PLT+ Total SOFA）,SIC 1.positive 2.negative
0,1,72.0,1,2,41.0,17.00,2,2,4,1,3,3,1,2,0,5,2,4,2
1,2,76.0,1,2,23.0,18.70,3,1,6,1,2,3,2,4,2,8,4,6,1
2,1,93.0,2,2,57.0,22.90,3,1,6,1,1,2,1,0,0,2,4,6,1
3,2,76.0,2,2,66.0,23.40,2,2,5,1,3,2,2,4,4,8,3,5,1
4,1,76.0,2,2,44.0,3.90,4,1,4,1,0,3,0,1,3,3,2,4,2
5,1,69.0,2,2,13.0,5.30,3,1,5,1,0,1,0,0,0,0,4,4,2
6,2,63.0,1,2,53.0,54.50,4,1,8,1,4,2,2,4,1,7,4,6,1
7,1,84.0,2,2,79.0,5.80,0,2,3,2,0,3,1,0,0,1,2,3,2
8,1,69.0,1,2,77.0,13.50,3,1,5,1,3,2,0,0,1,3,2,4,2
9,1,63.0,1,2,31.0,77.80,3,1,8,1,3,3,3,2,3,8,4,6,1
10,1,67.0,1,2,69.0,23.60,3,1,6,1,2,2,2,4,2,8,4,6,1
11,2,73.0,2,2,69.0,20.00,2,2,5,1,0,2,0,0,0,0,3,3,2
12,2,71.0,2,1,70.0,13.00,3,1,6,1,2,2,0,0,0,2,3,5,1
13,2,68.0,2,2,78.0,27.40,1,2,7,1,2,2,0,0,3,4,4,6,1
14,2,61.0,1,2,74.0,3.70,2,2,3,2,0,2,0,1,3,3,2,4,2
15,2,84.0,2,2,38.0,15.80,4,1,6,1,0,3,2,2,1,5,4,6,1
16,1,73.0,2,2,150.0,40.80,1,2,4,1,2,0,0,3,4,6,2,4,2
17,1,64.0,1,2,69.0,32.20,3,1,8,1,2,2,3,4,3,8,3,5,1
18,1,34.0,1,2,40.0,45.40,2,2,7,1,3,3,2,3,4,8,4,6,1
19,1,72.0,1,2,73.0,19.80,3,1,6,1,2,2,2,4,0,6,3,5,1
20,2,83.0,2,2,99.0,20.90,2,2,3,2,4,2,0,3,0,4,3,5,1
21,2,77.0,2,2,80.0,180.00,3,1,6,1,3,2,0,3,2,6,4,6,1
22,2,63.0,2,2,37.0,20.90,4,1,6,1,4,3,0,3,0,4,4,6,1
23,1,36.0,1,2,65.0,5.00,4,1,5,1,1,2,0,0,0,1,4,5,1
24,1,70.0,2,2,22.0,103.00,3,1,7,1,2,3,0,0,1,3,2,4,2
25,1,78.0,2,2,49.0,62.30,2,2,7,1,4,3,0,2,2,6,3,5,1
26,1,68.0,2,2,55.0,28.00,3,1,7,1,4,2,0,4,4,6,2,4,2
27,2,87.0,2,2,74.0,10.20,2,2,5,1,3,2,0,4,1,5,3,5,1
28,1,66.0,1,2,12.0,11.00,3,1,6,1,2,4,2,1,0,5,3,5,1
29,2,19.0,1,2,48.0,140.80,4,1,8,1,1,3,1,2,0,4,4,6,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1468,1,83.0,2,2,56.0,15.30,4,1,6,1,1,2,2,2,0,5,4,6,1
1469,1,87.0,2,2,135.0,34.00,2,2,4,1,0,1,0,3,0,2,3,5,1
1470,2,88.0,2,2,65.0,19.80,3,1,6,1,4,2,1,2,0,5,4,6,1
1471,1,69.0,2,2,106.0,25.30,3,1,3,2,3,1,1,4,0,5,1,3,2
1472,2,65.0,1,2,7.0,33.20,0,2,7,1,3,4,3,3,4,8,4,6,1
1473,1,69.0,2,2,27.0,15.60,4,1,6,1,4,3,2,3,2,8,4,6,1
1474,2,73.0,1,2,48.0,20.70,2,2,5,1,0,3,1,2,0,3,4,6,1
1475,1,93.0,2,2,40.0,23.70,3,1,6,1,2,3,3,1,2,7,3,5,1
1476,1,81.0,2,2,32.0,31.60,3,1,8,1,0,3,2,0,1,3,4,6,1
1477,1,47.0,2,2,80.0,12.40,3,1,4,1,1,2,0,1,0,2,4,6,1
1478,1,75.0,2,1,30.0,10.50,2,2,4,1,1,3,1,0,0,2,2,4,2
1479,2,89.0,2,2,227.0,80.00,4,1,5,1,0,0,1,0,1,2,2,4,2
1480,1,86.0,2,2,57.0,25.30,2,2,4,1,4,2,0,3,0,4,4,6,1
1481,2,83.0,2,1,30.0,8.00,3,1,5,1,0,3,0,1,0,1,2,3,2
1482,1,67.0,2,2,65.0,19.20,2,2,4,1,4,2,0,4,3,6,2,4,2
1483,1,71.0,1,2,40.0,8.30,3,1,5,1,3,3,0,0,0,2,3,5,1
1484,1,76.0,2,2,21.0,5.00,4,1,5,1,4,3,2,3,0,6,3,5,1
1485,2,76.0,1,2,92.0,7.86,3,1,3,2,1,2,0,1,0,2,4,6,1
1486,2,42.0,1,2,96.0,25.30,4,1,4,1,2,2,0,1,0,3,3,5,1
1487,2,65.0,2,2,51.0,45.90,3,1,8,1,1,2,0,0,1,2,3,5,1
1488,1,88.0,2,2,64.0,14.02,2,2,5,1,2,2,0,0,1,3,3,5,1
1489,2,74.0,1,2,89.0,91.90,4,1,6,1,4,2,0,4,3,6,4,6,1
1490,1,6.0,2,2,26.0,25.30,4,1,8,1,2,3,0,2,2,6,4,6,1
1491,1,60.0,2,2,33.0,73.50,1,2,7,1,2,3,1,3,0,5,3,5,1
1492,2,58.0,2,2,105.0,19.00,2,2,3,2,1,1,0,3,4,5,2,4,2
1493,1,84.0,2,2,40.0,49.40,2,2,7,1,2,3,1,2,0,5,3,5,1
1494,1,4.0,2,2,283.0,586.20,2,2,4,1,4,0,0,3,0,4,2,4,2
1495,1,65.0,1,2,28.0,71.00,3,1,7,1,1,3,2,3,1,6,2,4,2
1496,1,80.0,1,2,55.0,15.10,1,2,5,1,4,2,0,4,4,6,4,6,1
1497,1,82.0,1,2,25.0,37.10,4,1,8,1,3,3,2,3,1,7,4,6,1

In [20]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1498 entries, 0 to 1497
Data columns (total 19 columns):
Sex
1.Male
2.Female                       1498 non-null int64
Age                                       1498 non-null float64
Before
treatment                          1498 non-null int64
Severity
1.mild/moderate
2.severe         1498 non-null int64
Platelet                                  1498 non-null float64
FDP                                       1498 non-null float64
SIRS_t1                                   1498 non-null int64
SIRS
3 or more
1. positive
2. negative    1498 non-null int64
JAAM DIC
score                            1498 non-null int64
JAAM
DIC
1.positive
2.negative            1498 non-null int64
SOFA
respiratory                          1498 non-null int64
SOFA
coagulation                          1498 non-null int64
SOFA
hepatic                              1498 non-null int64
SOFA
cardiovascular                       1498 non-null int64
SOFA
renal                                1498 non-null int64
Total SOFA
(4 items)                      1498 non-null int64
SIC score
(PT+PLT)                        1498 non-null int64
SIC score（PT+PLT+
 Total SOFA）            1498 non-null int64
SIC
1.positive
2.negative                 1498 non-null int64
dtypes: float64(3), int64(16)
memory usage: 234.1 KB

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(1498, 19)
[[-1. 72. -1. ...  2.  4.  1.]
 [ 1. 76. -1. ...  4.  6. -1.]
 [-1. 93.  1. ...  4.  6. -1.]
 ...
 [-1. 65. -1. ...  2.  4.  1.]
 [-1. 80. -1. ...  4.  6. -1.]
 [-1. 82. -1. ...  4.  6. -1.]]

### Target

In [23]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# convert target to 0 and 1
y_new = np.ones(y.shape[0])
y_new[y ==2] = 0

# if target is already 0 and 1
#y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([1, 2]), array([994, 504]))
(array([0., 1.]), array([504, 994]))

In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('coag_processed.dat',xy_new,fmt='%f')