## Data cleaning

In this section, we first see the data structure and identify data attributes. We then clean the data, including removing bad rows, bad attributes, imputing missing values, etc.

First of all, we import the necessary packages to the Jupyter notebook:

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(1)

We load the raw data.

In [3]:
df = pd.read_csv('paradox.csv',sep= ',')

In [4]:
df.head()

,Site,Code,SAincl,SA2,SA4,SA6,SA8,SA10,SA12,SA1416,...,TempPara5,VitD,VitD3Groups,ThreeUTR,ThreeUTRvar,INT4,INT4var,D543,Callele,Callelevar
0,1.0,401,8.3,1.0,2.8,3.3,1.2,1.1,1.1,1.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,402,11.3,13.3,18.9,20.1,26.2,34.7,29.9,33.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,403,15.4,9.9,9.5,9.5,8.3,8.7,6.4,3.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,404,0.5,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,405,33.0,24.1,12.3,11.8,8.7,3.3,3.1,3.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Dropping the column `code` as it is unrelated to the dependent variable

In [5]:
df = df.drop(['Code','WeekParadox3','lesnumbincl','PulsePara3','PulsePara5','TempPara3','TempPara5'],axis=1)

The dependent variable is the presence of a paradoxical response: paradox1.

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 42 columns):
Site                     241 non-null float64
SAincl                   241 non-null float64
SA2                      233 non-null float64
SA4                      227 non-null float64
SA6                      223 non-null float64
SA8                      232 non-null float64
SA10                     215 non-null float64
SA12                     225 non-null float64
SA1416                   223 non-null float64
SA2120                   221 non-null float64
SA2728                   211 non-null float64
studyarm                 241 non-null float64
sexe                     241 non-null float64
age                      241 non-null int64
lesionsince              240 non-null float64
BPSYST                   216 non-null float64
BPDIAST                  216 non-null float64
pulserateinclbeatsmin    232 non-null float64
tempinclCelsius          237 non-null float64
bodyweightinclkg         241 non-null int64
bodyheightinclcm         237 non-null float64
WHOCat                   241 non-null float64
stageincllesion          241 non-null int64
oedemaincl               241 non-null int64
Sitelesion               239 non-null float64
Hb                       237 non-null float64
WBC                      237 non-null float64
creatin                  240 non-null float64
HIV                      241 non-null float64
Drug                     241 non-null float64
Paradox1                 241 non-null float64
Paradox2                 241 non-null float64
WeekParadox5             241 non-null float64
VitD                     144 non-null float64
VitD3Groups              144 non-null float64
ThreeUTR                 150 non-null float64
ThreeUTRvar              150 non-null float64
INT4                     150 non-null float64
INT4var                  150 non-null float64
D543                     150 non-null float64
Callele                  150 non-null float64
Callelevar               150 non-null float64
dtypes: float64(38), int64(4)
memory usage: 79.2 KB

To clearn the data, we first replace the empty value by `nan`.

In [7]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

,Site,SAincl,SA2,SA4,SA6,SA8,SA10,SA12,SA1416,SA2120,...,WeekParadox5,VitD,VitD3Groups,ThreeUTR,ThreeUTRvar,INT4,INT4var,D543,Callele,Callelevar
0,1.0,8.3,1.0,2.8,3.3,1.2,1.1,1.1,1.1,0.0,...,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.0,11.3,13.3,18.9,20.1,26.2,34.7,29.9,33.0,33.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.0,15.4,9.9,9.5,9.5,8.3,8.7,6.4,3.9,3.7,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,0.5,0.2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.0,33.0,24.1,12.3,11.8,8.7,3.3,3.1,3.1,7.1,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,6.4,21.4,3.9,6.0,7.1,6.7,2.8,6.4,5.0,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1.0,3.3,1.3,0.2,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,3.6,3.3,0.6,0.5,0.2,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,1.0,6.4,7.9,6.0,4.8,2.6,0.3,1.8,1.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.0,9.1,7.9,7.9,5.7,4.1,2.0,2.8,4.1,0.0,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,1.0,17.7,7.9,8.7,1.3,1.6,6.4,3.9,4.4,1.3,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,1.0,9.9,11.3,8.7,7.9,22.7,15.4,16.5,20.1,0.0,...,16.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,1.0,4.4,0.5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1.0,88.2,74.3,80.5,68.4,36.3,34.7,68.4,26.2,14.3,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,1.0,22.7,6.4,7.9,5.0,4.4,3.9,5.8,3.3,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,1.0,2.8,5.0,2.4,2.4,1.6,1.1,2.4,1.3,0.5,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,1.0,22.7,17.7,4.4,2.0,1.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,1.0,24.1,17.7,21.4,16.5,16.7,12.3,17.7,17.7,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1.0,9.5,9.5,7.1,7.1,5.7,5.7,7.5,6.0,3.3,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,1.0,3.6,2.4,1.6,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1.0,0.2,0.2,0.1,0.2,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1.0,1.4,2.8,0.1,0.2,0.2,0.1,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1.0,7.9,3.9,3.9,2.4,2.4,3.0,1.5,2.2,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1.0,7.1,9.5,3.9,5.0,3.6,4.4,0.0,2.0,1.3,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1.0,19.5,22.7,13.8,14.3,14.9,14.3,15.4,0.0,0.7,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1.0,47.2,18.9,28.4,22.0,24.1,11.8,14.3,5.0,2.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1.0,4.7,3.6,3.6,3.6,4.4,2.4,2.4,2.2,0.2,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,1.0,29.9,22.7,23.4,22.0,45.3,25.6,36.3,38.0,38.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,1.0,22.7,24.8,25.5,30.6,24.1,24.3,0.0,0.0,0.0,...,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,1.0,4.4,4.4,3.3,3.3,3.9,5.0,2.2,3.3,0.0,...,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
211,2.0,13.2,8.4,8.9,1.6,1.2,11.5,9.4,9.8,7.1,...,0.0,60.9,2.0,1.0,1.0,0.0,0.0,1.0,2.0,1.0
212,2.0,36.9,16.0,9.0,11.0,NaN,8.9,6.5,6.8,NaN,...,0.0,59.4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
213,2.0,16.1,8.9,12.8,4.3,4.1,1.9,2.1,3.7,0.0,...,16.0,103.5,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
214,2.0,48.4,3.0,2.1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,NaN,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0
215,2.0,55.5,37.7,27.7,10.5,6.9,6.8,12.6,3.4,0.7,...,0.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
216,2.0,8.2,5.9,4.7,3.9,2.5,NaN,0.6,0.8,0.0,...,0.0,70.8,2.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
217,2.0,5.4,2.6,2.3,2.8,1.7,NaN,0.0,0.0,0.0,...,0.0,74.1,2.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
218,2.0,72.4,50.4,112.3,NaN,125.6,101.9,96.3,88.3,66.4,...,0.0,99.2,3.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
219,2.0,25.6,10.4,9.1,1.9,2.5,NaN,NaN,NaN,NaN,...,0.0,64.8,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
220,2.0,71.3,38.6,38.1,26.1,29.4,22.7,16.3,14.1,11.4,...,0.0,61.2,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
221,2.0,28.7,19.2,17.4,NaN,3.7,1.8,1.4,NaN,0.7,...,0.0,38.2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
222,2.0,46.7,38.7,57.1,NaN,60.2,NaN,34.2,20.0,11.4,...,0.0,53.3,1.0,1.0,1.0,2.0,1.0,1.0,0.0,0.0
223,2.0,44.3,74.5,135.4,58.0,52.6,49.5,24.9,17.9,16.9,...,0.0,94.7,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
224,2.0,20.6,15.7,18.2,19.3,18.0,NaN,23.5,15.3,2.3,...,6.0,78.3,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
225,2.0,50.6,54.5,58.8,54.6,82.0,84.7,NaN,54.5,35.0,...,0.0,86.6,3.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0
226,2.0,24.1,15.4,22.2,NaN,30.2,28.1,20.2,19.8,9.6,...,0.0,85.2,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
227,2.0,77.4,49.0,27.3,30.2,19.2,15.1,14.5,12.9,10.3,...,0.0,67.5,2.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0
228,2.0,78.0,139.5,108.0,104.8,NaN,88.6,50.0,NaN,20.4,...,0.0,63.6,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
229,2.0,7.7,4.3,4.4,1.5,0.9,1.9,NaN,0.7,0.0,...,0.0,90.2,3.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0
230,2.0,54.6,45.7,40.5,NaN,21.7,23.0,16.4,19.9,19.9,...,0.0,89.6,3.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
231,2.0,6.5,7.1,2.1,1.3,1.8,3.4,5.6,3.2,3.6,...,10.0,42.7,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
232,2.0,39.3,42.4,58.2,39.8,66.0,106.1,NaN,78.9,326.1,...,10.0,68.2,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
233,2.0,21.1,21.9,12.4,7.7,4.1,3.8,2.8,1.2,1.8,...,0.0,68.1,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
234,2.0,6.5,5.6,2.6,0.9,1.9,0.9,0.7,1.3,0.0,...,0.0,55.9,1.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
235,2.0,13.3,2.2,4.2,0.9,1.2,1.2,4.3,0.4,8.0,...,0.0,76.8,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
236,2.0,60.8,35.0,46.5,NaN,58.5,80.8,93.4,48.8,17.2,...,0.0,77.4,3.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0
237,2.0,0.5,1.7,0.4,0.4,0.3,0.6,0.0,0.0,0.0,...,0.0,57.5,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
238,2.0,38.4,NaN,33.9,40.6,51.8,21.6,NaN,34.3,33.4,...,0.0,77.6,3.0,0.0,0.0,0.0,0.0,0.0,2.0,1.0
239,2.0,68.1,79.2,74.5,55.4,72.6,78.7,73.9,37.0,27.3,...,10.0,44.1,1.0,2.0,1.0,0.0,0.0,1.0,1.0,1.0
240,2.0,4.0,1.5,1.1,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,58.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 42 columns):
Site                     241 non-null float64
SAincl                   241 non-null float64
SA2                      233 non-null float64
SA4                      227 non-null float64
SA6                      223 non-null float64
SA8                      232 non-null float64
SA10                     215 non-null float64
SA12                     225 non-null float64
SA1416                   223 non-null float64
SA2120                   221 non-null float64
SA2728                   211 non-null float64
studyarm                 241 non-null float64
sexe                     241 non-null float64
age                      241 non-null int64
lesionsince              240 non-null float64
BPSYST                   216 non-null float64
BPDIAST                  216 non-null float64
pulserateinclbeatsmin    232 non-null float64
tempinclCelsius          237 non-null float64
bodyweightinclkg         241 non-null int64
bodyheightinclcm         237 non-null float64
WHOCat                   241 non-null float64
stageincllesion          241 non-null int64
oedemaincl               241 non-null int64
Sitelesion               239 non-null float64
Hb                       237 non-null float64
WBC                      237 non-null float64
creatin                  240 non-null float64
HIV                      241 non-null float64
Drug                     241 non-null float64
Paradox1                 241 non-null float64
Paradox2                 241 non-null float64
WeekParadox5             241 non-null float64
VitD                     144 non-null float64
VitD3Groups              144 non-null float64
ThreeUTR                 150 non-null float64
ThreeUTRvar              150 non-null float64
INT4                     150 non-null float64
INT4var                  150 non-null float64
D543                     150 non-null float64
Callele                  150 non-null float64
Callelevar               150 non-null float64
dtypes: float64(38), int64(4)
memory usage: 79.2 KB

The data still contain errors, such as `\t`, ` `, `\?`. We will delete `\t` and ` ` and convert `\?` to `np.nan`.

In [9]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

We determine and drop the variables with excessive missing values from the dataset.

In [10]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] > bad_column_threshold:
            bad_col = np.append(bad_col,t)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df

In [11]:
df = remove_bad_columns(df,40)

number of bad columns: 9

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 241 entries, 0 to 240
Data columns (total 33 columns):
Site                     241 non-null float64
SAincl                   241 non-null float64
SA2                      233 non-null float64
SA4                      227 non-null float64
SA6                      223 non-null float64
SA8                      232 non-null float64
SA10                     215 non-null float64
SA12                     225 non-null float64
SA1416                   223 non-null float64
SA2120                   221 non-null float64
SA2728                   211 non-null float64
studyarm                 241 non-null float64
sexe                     241 non-null float64
age                      241 non-null int64
lesionsince              240 non-null float64
BPSYST                   216 non-null float64
BPDIAST                  216 non-null float64
pulserateinclbeatsmin    232 non-null float64
tempinclCelsius          237 non-null float64
bodyweightinclkg         241 non-null int64
bodyheightinclcm         237 non-null float64
WHOCat                   241 non-null float64
stageincllesion          241 non-null int64
oedemaincl               241 non-null int64
Sitelesion               239 non-null float64
Hb                       237 non-null float64
WBC                      237 non-null float64
creatin                  240 non-null float64
HIV                      241 non-null float64
Drug                     241 non-null float64
Paradox1                 241 non-null float64
Paradox2                 241 non-null float64
WeekParadox5             241 non-null float64
dtypes: float64(29), int64(4)
memory usage: 62.2 KB

We find bad rows which contain too many missing values, then remove them.

In [13]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([])
    for t in range(len(n_null)):
        if n_null[t] > bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [14]:
df = remove_bad_rows(df,5)

number of bad rows: 5

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 240
Data columns (total 33 columns):
Site                     236 non-null float64
SAincl                   236 non-null float64
SA2                      229 non-null float64
SA4                      224 non-null float64
SA6                      221 non-null float64
SA8                      229 non-null float64
SA10                     215 non-null float64
SA12                     224 non-null float64
SA1416                   222 non-null float64
SA2120                   219 non-null float64
SA2728                   210 non-null float64
studyarm                 236 non-null float64
sexe                     236 non-null float64
age                      236 non-null int64
lesionsince              235 non-null float64
BPSYST                   212 non-null float64
BPDIAST                  212 non-null float64
pulserateinclbeatsmin    228 non-null float64
tempinclCelsius          232 non-null float64
bodyweightinclkg         236 non-null int64
bodyheightinclcm         232 non-null float64
WHOCat                   236 non-null float64
stageincllesion          236 non-null int64
oedemaincl               236 non-null int64
Sitelesion               234 non-null float64
Hb                       233 non-null float64
WBC                      233 non-null float64
creatin                  235 non-null float64
HIV                      236 non-null float64
Drug                     236 non-null float64
Paradox1                 236 non-null float64
Paradox2                 236 non-null float64
WeekParadox5             236 non-null float64
dtypes: float64(29), int64(4)
memory usage: 62.7 KB

For convenience, we separate independents `X` and dependent `y` from the data.

In [16]:
X = df.drop('Paradox1',axis=1)
y = df['Paradox1']

We impute the missing value of X at each column by its median value.

In [17]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):
    def __init__(self):
        """Impute missing values.
        - Columns of dtype object are imputed with the most frequent value in column.
        - Columns of other types are imputed with mean of column.
        """
    def fit(self, X, y=None):
        self.fill = pd.Series([X[c].value_counts().index[0]
            # numerical --> mean, categorical --> median
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X], index=X.columns)  
                               
            # numerical, categorical --> median                   
            #if X[c].dtype == np.dtype('O') else X[c].median() for c in X], index=X.columns)
        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [18]:
X = DataFrameImputer().fit_transform(X)

In [19]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 236 entries, 0 to 240
Data columns (total 32 columns):
Site                     236 non-null float64
SAincl                   236 non-null float64
SA2                      236 non-null float64
SA4                      236 non-null float64
SA6                      236 non-null float64
SA8                      236 non-null float64
SA10                     236 non-null float64
SA12                     236 non-null float64
SA1416                   236 non-null float64
SA2120                   236 non-null float64
SA2728                   236 non-null float64
studyarm                 236 non-null float64
sexe                     236 non-null float64
age                      236 non-null int64
lesionsince              236 non-null float64
BPSYST                   236 non-null float64
BPDIAST                  236 non-null float64
pulserateinclbeatsmin    236 non-null float64
tempinclCelsius          236 non-null float64
bodyweightinclkg         236 non-null int64
bodyheightinclcm         236 non-null float64
WHOCat                   236 non-null float64
stageincllesion          236 non-null int64
oedemaincl               236 non-null int64
Sitelesion               236 non-null float64
Hb                       236 non-null float64
WBC                      236 non-null float64
creatin                  236 non-null float64
HIV                      236 non-null float64
Drug                     236 non-null float64
Paradox2                 236 non-null float64
WeekParadox5             236 non-null float64
dtypes: float64(28), int64(4)
memory usage: 60.8 KB

Now, the data are completely clean. We convert attributes `X` and target `y` to numpy arrays and save them to files.

In [20]:
X = np.array(X)
y = np.array(y)
Xy = np.hstack((X,y[:,np.newaxis]))

np.savetxt('paradox_cleaned.dat',Xy,fmt='%s')