## Data cleaning

In this section, we first see the data structure and identify data attributes. We then clean the data, including removing bad rows, bad attributes, imputing missing values, etc.

First of all, we import the necessary packages to the Jupyter notebook:

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(1)

We load the raw data.

In [3]:
df = pd.read_csv('coimbra.csv',sep= ',')

In [4]:
df.head()

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1

The dependent variable is the classification of study result for coimbra patients.

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
Age               116 non-null int64
BMI               116 non-null float64
Glucose           116 non-null int64
Insulin           116 non-null float64
HOMA              116 non-null float64
Leptin            116 non-null float64
Adiponectin       116 non-null float64
Resistin          116 non-null float64
MCP.1             116 non-null float64
Classification    116 non-null int64
dtypes: float64(7), int64(3)
memory usage: 9.1 KB

To clearn the data, we first replace the empty value by `nan`.

In [6]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

,Age,BMI,Glucose,Insulin,HOMA,Leptin,Adiponectin,Resistin,MCP.1,Classification
0,48,23.500000,70,2.707,0.467409,8.8071,9.702400,7.99585,417.114,1
1,83,20.690495,92,3.115,0.706897,8.8438,5.429285,4.06405,468.786,1
2,82,23.124670,91,4.498,1.009651,17.9393,22.432040,9.27715,554.697,1
3,68,21.367521,77,3.226,0.612725,9.8827,7.169560,12.76600,928.220,1
4,86,21.111111,92,3.549,0.805386,6.6994,4.819240,10.57635,773.920,1
5,49,22.854458,92,3.226,0.732087,6.8317,13.679750,10.31760,530.410,1
6,89,22.700000,77,4.690,0.890787,6.9640,5.589865,12.93610,1256.083,1
7,76,23.800000,118,6.470,1.883201,4.3110,13.251320,5.10420,280.694,1
8,73,22.000000,97,3.350,0.801543,4.4700,10.358725,6.28445,136.855,1
9,75,23.000000,83,4.952,1.013839,17.1270,11.578990,7.09130,318.302,1
10,34,21.470000,78,3.469,0.667436,14.5700,13.110000,6.92000,354.600,1
11,29,23.010000,82,5.663,1.145436,35.5900,26.720000,4.58000,174.800,1
12,25,22.860000,82,4.090,0.827271,20.4500,23.670000,5.14000,313.730,1
13,24,18.670000,88,6.107,1.330000,8.8800,36.060000,6.85000,632.220,1
14,38,23.340000,75,5.782,1.069670,15.2600,17.950000,9.35000,165.020,1
15,44,20.760000,86,7.553,1.600000,14.0900,20.320000,7.64000,63.610,1
16,47,22.030000,84,2.869,0.590000,26.6500,38.040000,3.32000,191.720,1
17,61,32.038959,85,18.077,3.790144,30.7729,7.780255,13.68392,444.395,1
18,64,34.529723,95,4.427,1.037394,21.2117,5.462620,6.70188,252.449,1
19,32,36.512637,87,14.026,3.009980,49.3727,5.100000,17.10223,588.460,1
20,36,28.576676,86,4.345,0.921719,15.1248,8.600000,9.15390,534.224,1
21,34,31.975015,87,4.530,0.972138,28.7502,7.642760,5.62592,572.783,1
22,29,32.270788,84,5.810,1.203832,45.6196,6.209635,24.60330,904.981,1
23,35,30.276817,84,4.376,0.906707,39.2134,9.048185,16.43706,733.797,1
24,54,30.483158,90,5.537,1.229214,12.3310,9.731380,10.19299,1227.910,1
25,45,37.035608,83,6.760,1.383997,39.9802,4.617125,8.70448,586.173,1
26,50,38.578759,106,6.703,1.752611,46.6401,4.667645,11.78388,887.160,1
27,66,31.446541,90,9.245,2.052390,45.9624,10.355260,23.38190,1102.110,1
28,35,35.250761,90,6.817,1.513374,50.6094,6.966895,22.03703,667.928,1
29,36,34.174890,80,6.590,1.300427,10.2809,5.065915,15.72187,581.313,1
...,...,...,...,...,...,...,...,...,...,...
86,48,28.125000,90,2.540,0.563880,15.5325,10.222310,16.11032,1698.440,2
87,85,27.688778,196,51.814,25.050342,70.8824,7.901685,55.21530,1078.359,2
88,48,31.250000,199,12.162,5.969920,18.1314,4.104105,53.63080,1698.440,2
89,58,29.154519,139,16.582,5.685415,22.8884,10.262660,13.97399,923.886,2
90,40,30.836531,128,41.894,13.227332,31.0385,6.160995,17.55503,638.261,2
91,82,31.217482,100,18.077,4.458993,31.6453,9.923650,19.94687,994.316,2
92,52,30.801249,87,30.212,6.483495,29.2739,6.268540,24.24591,764.667,2
93,49,32.461911,134,24.887,8.225983,42.3914,10.793940,5.76800,656.393,2
94,60,31.231410,131,30.130,9.736007,37.8430,8.404430,11.50005,396.021,2
95,49,29.777778,70,8.396,1.449709,51.3387,10.731740,20.76801,602.486,2
96,44,27.887617,99,9.208,2.248594,12.6757,5.478170,23.03306,407.206,2
97,40,27.636054,103,2.432,0.617890,14.3224,6.783870,26.01360,293.123,2
98,71,27.915519,104,18.200,4.668907,53.4997,1.656020,49.24184,256.001,2
99,69,28.444444,108,8.808,2.346451,14.7485,5.288025,16.48508,353.568,2
100,74,28.650138,88,3.012,0.653805,31.1233,7.652220,18.35574,572.401,2
101,66,26.562500,89,6.524,1.432235,14.9084,8.429960,14.91922,269.487,2
102,65,30.915577,97,10.491,2.510147,44.0217,3.710090,20.46850,396.648,2
103,72,29.136316,83,10.949,2.241625,26.8081,2.784910,14.76966,232.018,2
104,57,34.838148,95,12.548,2.940415,33.1612,2.364950,9.95420,655.834,2
105,73,37.109375,134,5.636,1.862886,41.4064,3.335665,6.89235,788.902,2
106,45,29.384757,90,4.713,1.046286,23.8479,6.644245,15.55625,621.273,2
107,46,33.180000,92,5.750,1.304867,18.6900,9.160000,8.89000,209.190,2
108,68,35.560000,131,8.150,2.633537,17.8700,11.900000,4.19000,198.400,2
109,75,30.480000,152,7.010,2.628283,50.5300,10.060000,11.73000,99.450,2
110,54,36.050000,119,11.910,3.495982,89.2700,8.010000,5.06000,218.280,2
111,45,26.850000,92,3.330,0.755688,54.6800,12.100000,10.96000,268.230,2
112,62,26.840000,100,4.530,1.117400,12.4500,21.420000,7.32000,330.160,2
113,65,32.050000,97,5.730,1.370998,61.4800,22.540000,10.33000,314.050,2
114,72,25.590000,82,2.820,0.570392,24.9600,33.750000,3.27000,392.460,2
115,86,27.180000,138,19.910,6.777364,90.2800,14.110000,4.35000,90.090,2

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 116 entries, 0 to 115
Data columns (total 10 columns):
Age               116 non-null int64
BMI               116 non-null float64
Glucose           116 non-null int64
Insulin           116 non-null float64
HOMA              116 non-null float64
Leptin            116 non-null float64
Adiponectin       116 non-null float64
Resistin          116 non-null float64
MCP.1             116 non-null float64
Classification    116 non-null int64
dtypes: float64(7), int64(3)
memory usage: 9.1 KB

We find bad rows which contain too many missing values, then remove them.

In [8]:
# find bad rows having too many missing values
n_null = np.array(df.isnull().sum(axis=1))
bad_row = np.array([])
for t in range(len(n_null)):
    if n_null[t] > 10:
        #print(t)
        bad_row = np.append(bad_row,t)
        
print(bad_row)
print(len(bad_row))

# delete bad rows
df = df.drop(bad_row)
df.info()

[]
0
<class 'pandas.core.frame.DataFrame'>
Int64Index: 116 entries, 0 to 115
Data columns (total 10 columns):
Age               116 non-null int64
BMI               116 non-null float64
Glucose           116 non-null int64
Insulin           116 non-null float64
HOMA              116 non-null float64
Leptin            116 non-null float64
Adiponectin       116 non-null float64
Resistin          116 non-null float64
MCP.1             116 non-null float64
Classification    116 non-null int64
dtypes: float64(7), int64(3)
memory usage: 10.0 KB

The data still contain errors, such as `\t`, ` `, `\?`. We will delete `\t` and ` ` and convert `\?` to `np.nan`.

In [9]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

For convenience, we separate independents `X` and dependent `y` from the data.

In [10]:
X = df.drop('Classification',axis=1)
y = df['Classification']

In [11]:
x1 = np.array(X)
x1

array([[ 48.        ,  23.5       ,  70.        , ...,   9.7024    ,
          7.99585   , 417.114     ],
       [ 83.        ,  20.69049454,  92.        , ...,   5.429285  ,
          4.06405   , 468.786     ],
       [ 82.        ,  23.12467037,  91.        , ...,  22.43204   ,
          9.27715   , 554.697     ],
       ...,
       [ 65.        ,  32.05      ,  97.        , ...,  22.54      ,
         10.33      , 314.05      ],
       [ 72.        ,  25.59      ,  82.        , ...,  33.75      ,
          3.27      , 392.46      ],
       [ 86.        ,  27.18      , 138.        , ...,  14.11      ,
          4.35      ,  90.09      ]])

We determine and drop the variables with excessive missing values from the dataset.

In [12]:
i_missing = []
for i in range(x1.shape[1]):
    n_missing = np.sum(np.isnan(x1[:,i]))
    if n_missing > 5:
        print(i,n_missing)
        i_missing.append(i)    
print(i_missing)

[]

In [13]:
x2 = np.delete(x1,i_missing,axis=1)
x2.shape

(116, 9)

We impute the missing value of X at each column by its median value.

In [14]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):
    def __init__(self):
        """Impute missing values.
        - Columns of dtype object are imputed with the most frequent value in column.
        - Columns of other types are imputed with mean of column.
        """
    def fit(self, X, y=None):
        self.fill = pd.Series([X[c].value_counts().index[0]
            # numerical --> mean, categorical --> median
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X], index=X.columns)  
                               
            # numerical, categorical --> median                   
            #if X[c].dtype == np.dtype('O') else X[c].median() for c in X], index=X.columns)
        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [15]:
X = DataFrameImputer().fit_transform(X)

In [16]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 116 entries, 0 to 115
Data columns (total 9 columns):
Age            116 non-null int64
BMI            116 non-null float64
Glucose        116 non-null int64
Insulin        116 non-null float64
HOMA           116 non-null float64
Leptin         116 non-null float64
Adiponectin    116 non-null float64
Resistin       116 non-null float64
MCP.1          116 non-null float64
dtypes: float64(7), int64(2)
memory usage: 9.1 KB

Now, the data are completely clean. We convert attributes `X` and target `y` to numpy arrays and save them to files.

In [17]:
X = np.array(X)
y = np.array(y)
Xy = np.hstack((X,y[:,np.newaxis]))

np.savetxt('coimbra_cleaned.dat',Xy,fmt='%s')