## Data cleaning

In this section, we first see the data structure and identify data attributes. We then clean the data, including removing bad rows, bad attributes, imputing missing values, etc.

First of all, we import the necessary packages to the Jupyter notebook:

In [1]:
import numpy as np
import pandas as pd

import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
np.random.seed(1)

We load the raw data.

In [3]:
df = pd.read_csv('heat.csv',sep= ',')

In [4]:
df.head()

,Sex_1male_2female,Age,Weather_1sunny_2cloudy_3rainy_4missing,Location_1outdoor_indoor,Functionaldependency_1notdisable_2disable,HT,HeartDisease,Pscyco,DM,CerevD,...,Plt,BUN,Cre,AST,ALT,CK,CRP,Admission1,ICU,Deadtodischarge
0,1.0,24.0,3.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,...,23.2,17.0,1.69,29.0,48.0,506.0,17.4,1.0,NaN,NaN
1,NaN,43.0,NaN,1.0,NaN,0.0,0.0,0.0,0.0,0.0,...,24.3,23.1,3.08,36.0,35.0,883.0,0.46,1.0,NaN,NaN
2,1.0,58.0,NaN,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,31.2,19.4,1.42,33.0,16.0,815.0,0.16,1.0,NaN,NaN
3,1.0,46.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,33.3,32.9,4.20,33.0,54.0,173.0,1,1.0,NaN,NaN
4,1.0,57.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,14.1,21.0,1.33,77.0,36.0,386.0,0.103,1.0,1.0,NaN

There are 35 attributes

and 1 class: `Deadtodischarge`

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3177 entries, 0 to 3176
Data columns (total 36 columns):
Sex_1male_2female                            3110 non-null float64
Age                                          3135 non-null float64
Weather_1sunny_2cloudy_3rainy_4missing       2567 non-null float64
Location_1outdoor_indoor                     1831 non-null float64
Functionaldependency_1notdisable_2disable    2797 non-null float64
HT                                           3175 non-null float64
HeartDisease                                 3175 non-null float64
Pscyco                                       3175 non-null float64
DM                                           3175 non-null float64
CerevD                                       3175 non-null float64
ParkinD                                      3175 non-null float64
CKD                                          3175 non-null float64
Dementia                                     3175 non-null float64
PreSBP                                       1882 non-null float64
PreRR                                        1552 non-null float64
PreGCSlessthan15                             2011 non-null float64
PreBT                                        1766 non-null float64
PreHR                                        1859 non-null float64
Abdminal                                     1819 non-null float64
Muscular                                     1573 non-null float64
GCS                                          3080 non-null float64
SBP                                          2942 non-null float64
BT                                           2700 non-null float64
HR                                           2834 non-null float64
WBC                                          2850 non-null float64
Ht                                           2787 non-null float64
Plt                                          2797 non-null float64
BUN                                          2822 non-null float64
Cre                                          2837 non-null float64
AST                                          2805 non-null float64
ALT                                          2801 non-null float64
CK                                           2620 non-null float64
CRP                                          2639 non-null object
Admission1                                   3001 non-null float64
ICU                                          2502 non-null float64
Deadtodischarge                              2810 non-null float64
dtypes: float64(35), object(1)
memory usage: 893.6+ KB

We see that `Location_1outdoor_indoor`, `PreSBP`, `PreRR`, `PreBT`, `PreHR`, `Abdminal`, `Muscular` contain so many missing values, so we will remove these attributes.

In [6]:
df = df.drop(['Location_1outdoor_indoor', 'PreSBP', 'PreRR','PreBT','PreHR','Abdminal','Muscular'],axis=1)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3177 entries, 0 to 3176
Data columns (total 29 columns):
Sex_1male_2female                            3110 non-null float64
Age                                          3135 non-null float64
Weather_1sunny_2cloudy_3rainy_4missing       2567 non-null float64
Functionaldependency_1notdisable_2disable    2797 non-null float64
HT                                           3175 non-null float64
HeartDisease                                 3175 non-null float64
Pscyco                                       3175 non-null float64
DM                                           3175 non-null float64
CerevD                                       3175 non-null float64
ParkinD                                      3175 non-null float64
CKD                                          3175 non-null float64
Dementia                                     3175 non-null float64
PreGCSlessthan15                             2011 non-null float64
GCS                                          3080 non-null float64
SBP                                          2942 non-null float64
BT                                           2700 non-null float64
HR                                           2834 non-null float64
WBC                                          2850 non-null float64
Ht                                           2787 non-null float64
Plt                                          2797 non-null float64
BUN                                          2822 non-null float64
Cre                                          2837 non-null float64
AST                                          2805 non-null float64
ALT                                          2801 non-null float64
CK                                           2620 non-null float64
CRP                                          2639 non-null object
Admission1                                   3001 non-null float64
ICU                                          2502 non-null float64
Deadtodischarge                              2810 non-null float64
dtypes: float64(28), object(1)
memory usage: 719.9+ KB

To clean the data, we first replace the empty value by `nan`.

In [8]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

,Sex_1male_2female,Age,Weather_1sunny_2cloudy_3rainy_4missing,Functionaldependency_1notdisable_2disable,HT,HeartDisease,Pscyco,DM,CerevD,ParkinD,...,Plt,BUN,Cre,AST,ALT,CK,CRP,Admission1,ICU,Deadtodischarge
0,1.0,24.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.2,17.0,1.690,29.00,48.0,506.0,17.4,1.0,NaN,NaN
1,NaN,43.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,24.3,23.1,3.080,36.00,35.0,883.0,0.46,1.0,NaN,NaN
2,1.0,58.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,31.2,19.4,1.420,33.00,16.0,815.0,0.16,1.0,NaN,NaN
3,1.0,46.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.3,32.9,4.200,33.00,54.0,173.0,1,1.0,NaN,NaN
4,1.0,57.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,14.1,21.0,1.330,77.00,36.0,386.0,0.103,1.0,1.0,NaN
5,1.0,29.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,29.7,13.9,0.850,16.00,18.0,230.0,0.01,0.0,0.0,0.0
6,1.0,49.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,23.4,13.5,0.760,100.00,56.0,2156.0,0.05,0.0,0.0,0.0
7,1.0,59.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.7,30.6,1.320,40.00,58.0,136.0,0.01,0.0,0.0,0.0
8,1.0,75.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.2,23.8,1.290,63.00,13.0,171.0,0.03,0.0,0.0,0.0
9,1.0,93.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,9.0,20.9,1.060,21.00,27.0,68.0,0.02,1.0,NaN,1.0
10,1.0,38.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30.4,14.8,0.610,37.00,18.0,1023.0,0.1,0.0,0.0,0.0
11,1.0,79.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,17.1,20.8,0.760,20.00,32.0,252.0,0.12,NaN,NaN,NaN
12,1.0,69.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,27.9,29.6,1.590,20.00,34.0,263.0,0.4,0.0,0.0,0.0
13,1.0,60.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,26.4,22.5,2.120,29.00,26.0,336.0,0.1,1.0,NaN,NaN
14,1.0,62.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,33.9,34.0,2.350,37.00,25.0,337.0,0.43,1.0,NaN,NaN
15,0.0,32.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
16,1.0,43.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,51.00,86.0,186.0,0.33,1.0,NaN,NaN
17,1.0,50.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,20.5,41.4,2.870,58.00,53.0,321.0,0.6,1.0,NaN,NaN
18,0.0,96.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,...,25.3,24.8,0.420,16.00,26.0,20.0,0.08,0.0,0.0,0.0
19,1.0,18.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.1,17.5,1.080,28.00,20.0,240.0,0.04,0.0,0.0,0.0
20,NaN,68.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,11.5,17.3,1.380,154.00,71.0,4157.0,0.08,1.0,1.0,NaN
21,1.0,78.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,21.0,22.5,1.000,42.00,25.0,1486.0,0.01,1.0,NaN,0.0
22,0.0,63.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.1,4.7,NaN,139.00,226.0,107.0,0.06,1.0,NaN,0.0
23,1.0,80.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,0.0,...,16.4,21.4,1.010,32.00,30.0,288.0,0.13,1.0,NaN,NaN
24,1.0,80.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,16.4,21.4,1.010,32.00,30.0,288.0,0.13,1.0,NaN,0.0
25,0.0,89.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,16.5,17.3,0.860,46.00,30.0,148.0,2.91,1.0,NaN,0.0
26,1.0,20.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,17.9,15.5,0.870,29.00,24.0,NaN,0.07,0.0,0.0,1.0
27,1.0,47.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,22.9,26.3,2.310,28.00,39.0,158.0,0.09,1.0,NaN,0.0
28,1.0,39.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
29,1.0,84.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,30.5,16.5,0.780,45.00,9.0,111.0,0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3147,1.0,38.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.7,20.4,1.240,51.00,59.0,10.4,0.46,NaN,NaN,NaN
3148,1.0,51.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,18.3,8.9,0.630,18.00,16.0,93.0,0.11,0.0,0.0,0.0
3149,1.0,38.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.1,15.4,0.090,20.00,24.0,180.0,0.62,0.0,0.0,0.0
3150,1.0,19.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,246.0,18.0,0.990,26.00,38.0,240.0,0.05,0.0,0.0,0.0
3151,1.0,31.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.1,27.5,1.330,42.00,79.0,270.0,0.21,0.0,0.0,0.0
3152,1.0,61.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0
3153,1.0,43.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.0,12.6,0.820,210.00,100.0,10371.0,0.71,1.0,1.0,0.0
3154,1.0,30.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,44.7,27.0,2.110,29.00,30.0,341.0,1.39,0.0,0.0,0.0
3155,1.0,56.0,1.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,...,224.0,36.0,3.100,30.00,20.0,730.0,0.15,0.0,0.0,0.0
3156,1.0,58.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,16.4,23.3,1.620,57.00,33.0,310.0,0.05,1.0,1.0,0.0
3157,1.0,47.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,235.0,12.0,0.890,117.00,100.0,332.0,0.06,0.0,0.0,0.0
3158,1.0,53.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,25.4,20.2,0.730,20.00,15.0,177.0,0.05,0.0,0.0,0.0
3159,0.0,74.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,17.0,18.1,0.960,37.00,42.0,147.0,0.06,0.0,0.0,0.0
3160,1.0,80.0,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,...,14.8,16.5,0.750,17.00,14.0,129.0,1.28,0.0,0.0,0.0
3161,1.0,51.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,23.7,20.0,1.743,144.00,91.0,341.0,0.3,1.0,1.0,0.0
3162,0.0,54.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6.4,34.0,1.170,2.04,28.0,192.0,0.1,1.0,1.0,0.0
3163,1.0,75.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,13.2,17.0,1.050,56.00,50.0,2439.0,0.1,1.0,1.0,0.0
3164,1.0,53.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,21.6,30.0,1.780,351.00,67.0,32160.0,0.9,1.0,1.0,0.0
3165,1.0,86.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,10.0,30.0,1.140,21.00,17.0,61.0,0.1,1.0,1.0,1.0
3166,0.0,69.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,24.4,29.0,2.120,91.00,24.0,883.0,0.1,1.0,1.0,NaN
3167,1.0,93.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,12.9,35.1,1.920,86.00,53.0,115.0,0.85,1.0,1.0,NaN
3168,1.0,56.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,21.0,8.6,0.890,123.00,52.0,6971.0,0.8,1.0,1.0,0.0
3169,1.0,65.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,19.3,16.9,1.190,40.00,34.0,225.0,0.16,1.0,1.0,0.0
3170,1.0,54.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,26.1,33.4,1.410,104.00,46.0,3836.0,3.7,1.0,1.0,0.0
3171,1.0,62.0,3.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,...,25.4,63.6,2.010,37.00,19.0,1606.0,1.29,1.0,1.0,1.0
3172,0.0,80.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,8.9,31.5,2.250,140.00,53.0,4388.0,10.74,1.0,1.0,0.0
3173,1.0,84.0,2.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,...,20.2,15.2,0.960,20.00,11.0,61.0,0.06,1.0,1.0,0.0
3174,1.0,82.0,NaN,1.0,0.0,0.0,1.0,0.0,1.0,0.0,...,25.0,26.9,1.320,26.00,19.0,109.0,0.09,1.0,1.0,0.0
3175,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3177 entries, 0 to 3176
Data columns (total 29 columns):
Sex_1male_2female                            3110 non-null float64
Age                                          3135 non-null float64
Weather_1sunny_2cloudy_3rainy_4missing       2567 non-null float64
Functionaldependency_1notdisable_2disable    2797 non-null float64
HT                                           3175 non-null float64
HeartDisease                                 3175 non-null float64
Pscyco                                       3175 non-null float64
DM                                           3175 non-null float64
CerevD                                       3175 non-null float64
ParkinD                                      3175 non-null float64
CKD                                          3175 non-null float64
Dementia                                     3175 non-null float64
PreGCSlessthan15                             2011 non-null float64
GCS                                          3080 non-null float64
SBP                                          2942 non-null float64
BT                                           2700 non-null float64
HR                                           2834 non-null float64
WBC                                          2850 non-null float64
Ht                                           2787 non-null float64
Plt                                          2797 non-null float64
BUN                                          2822 non-null float64
Cre                                          2837 non-null float64
AST                                          2805 non-null float64
ALT                                          2801 non-null float64
CK                                           2620 non-null float64
CRP                                          2639 non-null object
Admission1                                   3001 non-null float64
ICU                                          2502 non-null float64
Deadtodischarge                              2810 non-null float64
dtypes: float64(28), object(1)
memory usage: 719.9+ KB

The data still contain errors, such as `\t`, ` `, `\?`. We will delete `\t` and ` ` and convert `\?` to `np.nan`.

In [10]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

The current type of variable 'CRP' is object, we will convert them to numeric variable.

In [11]:
print(np.dtype(df['CRP']))

df["CRP"] = pd.to_numeric(df.CRP, errors='coerce')

object

We find bad rows which contain too many missing values, then remove them.

In [12]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([])
    for t in range(len(n_null)):
        if n_null[t] > bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [13]:
df = remove_bad_rows(df,5)

number of bad rows: 376

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2801 entries, 0 to 3174
Data columns (total 29 columns):
Sex_1male_2female                            2775 non-null float64
Age                                          2796 non-null float64
Weather_1sunny_2cloudy_3rainy_4missing       2327 non-null float64
Functionaldependency_1notdisable_2disable    2513 non-null float64
HT                                           2801 non-null float64
HeartDisease                                 2801 non-null float64
Pscyco                                       2801 non-null float64
DM                                           2801 non-null float64
CerevD                                       2801 non-null float64
ParkinD                                      2801 non-null float64
CKD                                          2801 non-null float64
Dementia                                     2801 non-null float64
PreGCSlessthan15                             1902 non-null float64
GCS                                          2734 non-null float64
SBP                                          2691 non-null float64
BT                                           2445 non-null float64
HR                                           2607 non-null float64
WBC                                          2788 non-null float64
Ht                                           2728 non-null float64
Plt                                          2748 non-null float64
BUN                                          2772 non-null float64
Cre                                          2778 non-null float64
AST                                          2758 non-null float64
ALT                                          2755 non-null float64
CK                                           2584 non-null float64
CRP                                          2594 non-null float64
Admission1                                   2730 non-null float64
ICU                                          2254 non-null float64
Deadtodischarge                              2541 non-null float64
dtypes: float64(29)
memory usage: 656.5 KB

We drop specific rows missing from the y variable, `Deadtodischarge`.

In [ ]:
df.drop(df.index[[2,3,30]])

We determine and drop the variables with excessive missing values from the dataset.

In [15]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] > bad_column_threshold:
            bad_col = np.append(bad_col,t)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df

In [16]:
df = remove_bad_columns(df,400)

number of bad columns: 3

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2801 entries, 0 to 3174
Data columns (total 26 columns):
Sex_1male_2female                            2775 non-null float64
Age                                          2796 non-null float64
Functionaldependency_1notdisable_2disable    2513 non-null float64
HT                                           2801 non-null float64
HeartDisease                                 2801 non-null float64
Pscyco                                       2801 non-null float64
DM                                           2801 non-null float64
CerevD                                       2801 non-null float64
ParkinD                                      2801 non-null float64
CKD                                          2801 non-null float64
Dementia                                     2801 non-null float64
GCS                                          2734 non-null float64
SBP                                          2691 non-null float64
BT                                           2445 non-null float64
HR                                           2607 non-null float64
WBC                                          2788 non-null float64
Ht                                           2728 non-null float64
Plt                                          2748 non-null float64
BUN                                          2772 non-null float64
Cre                                          2778 non-null float64
AST                                          2758 non-null float64
ALT                                          2755 non-null float64
CK                                           2584 non-null float64
CRP                                          2594 non-null float64
Admission1                                   2730 non-null float64
Deadtodischarge                              2541 non-null float64
dtypes: float64(26)
memory usage: 590.8 KB

For convenience, we separate independents `X` and dependent `y` from the data.

In [18]:
X = df.drop('Deadtodischarge',axis=1)
y = df['Deadtodischarge']

We impute the missing value of X at each column by its median value.

In [19]:
from sklearn.base import TransformerMixin

class DataFrameImputer(TransformerMixin):
    def __init__(self):
        """Impute missing values.
        - Columns of dtype object are imputed with the most frequent value in column.
        - Columns of other types are imputed with mean of column.
        """
    def fit(self, X, y=None):
        self.fill = pd.Series([X[c].value_counts().index[0]
            # numerical --> mean, categorical --> median
            if X[c].dtype == np.dtype('O') else X[c].mean() for c in X], index=X.columns)  
                               
            # numerical, categorical --> median                   
            #if X[c].dtype == np.dtype('O') else X[c].median() for c in X], index=X.columns)
        return self

    def transform(self, X, y=None):
        return X.fillna(self.fill)

In [20]:
X = DataFrameImputer().fit_transform(X)

In [21]:
X.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2801 entries, 0 to 3174
Data columns (total 25 columns):
Sex_1male_2female                            2801 non-null float64
Age                                          2801 non-null float64
Functionaldependency_1notdisable_2disable    2801 non-null float64
HT                                           2801 non-null float64
HeartDisease                                 2801 non-null float64
Pscyco                                       2801 non-null float64
DM                                           2801 non-null float64
CerevD                                       2801 non-null float64
ParkinD                                      2801 non-null float64
CKD                                          2801 non-null float64
Dementia                                     2801 non-null float64
GCS                                          2801 non-null float64
SBP                                          2801 non-null float64
BT                                           2801 non-null float64
HR                                           2801 non-null float64
WBC                                          2801 non-null float64
Ht                                           2801 non-null float64
Plt                                          2801 non-null float64
BUN                                          2801 non-null float64
Cre                                          2801 non-null float64
AST                                          2801 non-null float64
ALT                                          2801 non-null float64
CK                                           2801 non-null float64
CRP                                          2801 non-null float64
Admission1                                   2801 non-null float64
dtypes: float64(25)
memory usage: 569.0 KB

Now, the data are completely clean. We convert attributes `X` and target `y` to numpy arrays and save them to files.

In [22]:
X = np.array(X)
y = np.array(y)
Xy = np.hstack((X,y[:,np.newaxis]))

np.savetxt('heat_cleaned.dat',Xy,fmt='%s')