In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
#from sklearn.preprocessing import Imputer

In [2]:
np.random.seed(1)

In [3]:
df = pd.read_csv("tanzania.csv")
df

,GA,FHR_during_labour,Amniotic_fluid,Delivery_Mode,CS_category,CS_indication,BW,Apgar_1min,Apgar_5min,BMV,Outcome_30min,Outcome_24hours,Outcome_7days,Time_of_death,temp12ad0,puls13ad0,oxy14ad0,HIE_highest,major_cause,outcome
0,42.0,1,2,1,NaN,NaN,3000,8,10,2,2,2,3.0,2.0,36.0,144.0,60.0,NaN,6.0,1
1,40.0,9,1,1,NaN,NaN,2500,9,10,2,2,3,NaN,1.0,35.4,155.0,50.0,NaN,6.0,1
2,38.0,1,1,1,NaN,NaN,2815,7,10,1,1,2,3.0,2.0,36.4,166.0,71.0,NaN,6.0,1
3,36.0,1,1,1,NaN,NaN,2125,8,7,1,2,2,3.0,2.0,34.9,136.0,71.0,NaN,6.0,1
4,32.0,9,1,1,NaN,NaN,2115,9,10,2,2,2,3.0,3.0,36.1,131.0,72.0,NaN,6.0,1
5,36.0,1,1,1,NaN,NaN,2160,5,0,1,2,3,NaN,1.0,34.0,132.0,49.0,17.0,6.0,1
6,40.0,1,1,2,1.0,5.0,2085,9,10,2,2,2,3.0,2.0,35.0,136.0,96.0,NaN,6.0,1
7,38.0,1,1,1,NaN,NaN,2985,7,10,2,2,3,NaN,1.0,35.0,100.0,66.0,NaN,6.0,1
8,33.0,1,4,2,1.0,6.0,1660,9,10,2,2,2,3.0,2.0,36.7,158.0,53.0,NaN,6.0,1
9,40.0,9,1,1,NaN,NaN,2700,9,10,2,2,3,NaN,1.0,33.0,128.0,92.0,NaN,6.0,1
10,40.0,1,1,1,NaN,NaN,4070,9,10,2,2,3,NaN,1.0,36.4,146.0,86.0,NaN,6.0,1
11,40.0,1,1,2,1.0,3.0,4300,7,10,1,2,3,NaN,1.0,NaN,NaN,NaN,NaN,6.0,1
12,40.0,1,1,1,NaN,NaN,1950,7,10,2,2,2,3.0,2.0,NaN,139.0,52.0,NaN,6.0,1
13,36.0,1,1,2,2.0,3.0,2700,8,10,2,2,3,NaN,1.0,35.2,140.0,60.0,0.0,6.0,1
14,40.0,1,3,2,1.0,NaN,3335,5,8,1,2,2,3.0,2.0,35.0,139.0,37.0,NaN,5.0,1
15,38.0,2,3,2,1.0,2.0,2890,5,8,1,2,3,NaN,1.0,35.0,152.0,52.0,4.0,5.0,1
16,35.0,1,2,2,1.0,6.0,1930,7,10,1,2,2,3.0,2.0,35.4,152.0,37.0,NaN,5.0,1
17,36.0,1,3,1,NaN,NaN,3300,8,10,2,2,3,NaN,1.0,35.0,100.0,12.0,9.0,5.0,1
18,40.0,1,2,2,1.0,5.0,3400,8,10,2,1,2,3.0,2.0,NaN,145.0,55.0,NaN,5.0,1
19,40.0,1,3,2,1.0,3.0,3010,5,10,1,2,2,3.0,2.0,34.6,145.0,92.0,8.0,5.0,1
20,40.0,1,2,1,NaN,NaN,3000,7,10,1,2,3,NaN,1.0,36.5,132.0,90.0,NaN,5.0,1
21,NaN,1,3,1,NaN,NaN,3200,6,10,1,2,3,NaN,1.0,35.0,100.0,69.0,4.0,5.0,1
22,40.0,1,3,2,1.0,5.0,2430,6,10,1,2,3,NaN,1.0,33.6,133.0,40.0,6.0,5.0,1
23,36.0,1,3,2,1.0,1.0,3200,5,10,1,2,2,3.0,2.0,36.0,105.0,92.0,NaN,5.0,1
24,39.0,1,3,2,1.0,4.0,2900,6,10,1,2,3,NaN,1.0,36.0,132.0,64.0,NaN,5.0,1
25,40.0,1,2,2,1.0,3.0,2600,7,10,1,2,3,NaN,1.0,34.9,148.0,88.0,9.0,5.0,1
26,40.0,1,3,1,NaN,NaN,2500,6,8,2,2,2,3.0,3.0,36.4,161.0,78.0,7.0,5.0,1
27,30.0,1,1,3,NaN,NaN,1165,4,5,2,2,2,3.0,2.0,33.0,148.0,50.0,NaN,3.0,1
28,41.0,1,2,2,1.0,2.0,3420,3,5,1,2,3,NaN,1.0,35.0,158.0,79.0,18.0,3.0,1
29,40.0,1,3,1,NaN,NaN,2775,5,6,1,2,3,NaN,1.0,34.0,165.0,78.0,13.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,40.0,9,3,2,1.0,6.0,4250,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
642,NaN,9,3,1,NaN,NaN,3000,7,9,1,2,1,NaN,NaN,34.9,180.0,73.0,NaN,NaN,0
643,38.0,9,3,1,NaN,NaN,2450,7,10,2,2,1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0
644,40.0,9,1,2,1.0,5.0,2150,7,9,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
645,NaN,9,1,1,NaN,NaN,2550,2,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
646,37.0,9,1,1,NaN,NaN,3440,7,9,1,2,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
647,40.0,9,1,2,1.0,3.0,2390,6,9,1,2,2,1.0,NaN,34.0,141.0,83.0,NaN,NaN,0
648,38.0,9,4,2,1.0,6.0,2670,4,6,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
649,39.0,9,2,1,NaN,NaN,3000,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
650,34.0,1,1,1,NaN,NaN,2135,9,10,2,1,2,NaN,NaN,35.4,170.0,66.0,NaN,NaN,0
651,32.0,1,1,1,NaN,NaN,2165,9,10,2,1,2,NaN,NaN,35.7,168.0,56.0,NaN,NaN,0
652,40.0,2,3,2,1.0,2.0,2870,9,10,2,1,2,NaN,NaN,NaN,126.0,90.0,NaN,NaN,0
653,40.0,2,1,1,NaN,NaN,2300,9,10,2,1,2,NaN,NaN,35.0,135.0,82.0,NaN,NaN,0
654,39.0,2,1,2,1.0,2.0,2890,8,10,2,1,2,NaN,NaN,NaN,124.0,75.0,NaN,NaN,0
655,40.0,1,3,1,NaN,NaN,3295,4,7,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
656,36.0,1,3,2,1.0,2.0,3500,7,10,1,1,2,NaN,NaN,36.6,NaN,92.0,NaN,NaN,0
657,36.0,1,3,1,NaN,NaN,2340,9,10,2,1,2,NaN,NaN,NaN,136.0,95.0,NaN,NaN,0
658,40.0,1,3,1,NaN,NaN,3400,8,10,2,1,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0
659,NaN,1,1,2,1.0,5.0,1640,9,10,2,1,2,NaN,NaN,36.2,92.0,96.0,NaN,NaN,0
660,NaN,1,1,2,1.0,5.0,2160,8,10,2,1,2,NaN,NaN,34.1,105.0,91.0,NaN,NaN,0
661,39.0,1,1,1,NaN,NaN,2800,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
662,37.0,1,1,1,NaN,NaN,2700,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
663,36.0,1,1,1,NaN,NaN,3300,9,10,2,1,2,NaN,NaN,37.3,137.0,72.0,NaN,NaN,0
664,40.0,1,1,2,1.0,1.0,3200,9,10,2,1,2,NaN,NaN,34.0,157.0,94.0,NaN,NaN,0
665,38.0,1,1,1,NaN,NaN,3650,9,10,2,1,2,NaN,NaN,36.0,144.0,83.0,NaN,NaN,0
666,40.0,1,2,1,NaN,NaN,3500,5,8,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
667,40.0,1,2,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,34.9,164.0,98.0,NaN,NaN,0
668,40.0,1,2,1,NaN,NaN,3370,7,9,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
669,40.0,9,1,1,NaN,NaN,3400,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
670,NaN,9,1,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,33.0,124.0,92.0,NaN,NaN,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 20 columns):
GA                   599 non-null float64
FHR_during_labour    671 non-null int64
Amniotic_fluid       671 non-null int64
Delivery_Mode        671 non-null int64
CS_category          262 non-null float64
CS_indication        261 non-null float64
BW                   671 non-null int64
Apgar_1min           671 non-null int64
Apgar_5min           671 non-null int64
BMV                  671 non-null int64
Outcome_30min        671 non-null int64
Outcome_24hours      671 non-null int64
Outcome_7days        410 non-null float64
Time_of_death        124 non-null float64
temp12ad0            377 non-null float64
puls13ad0            363 non-null float64
oxy14ad0             371 non-null float64
HIE_highest          154 non-null float64
major_cause          124 non-null float64
outcome              671 non-null int64
dtypes: float64(10), int64(10)
memory usage: 104.9 KB

In [5]:
# replace empty by nan
df = df.replace(r'^\s+$', np.nan, regex=True)
df

,GA,FHR_during_labour,Amniotic_fluid,Delivery_Mode,CS_category,CS_indication,BW,Apgar_1min,Apgar_5min,BMV,Outcome_30min,Outcome_24hours,Outcome_7days,Time_of_death,temp12ad0,puls13ad0,oxy14ad0,HIE_highest,major_cause,outcome
0,42.0,1,2,1,NaN,NaN,3000,8,10,2,2,2,3.0,2.0,36.0,144.0,60.0,NaN,6.0,1
1,40.0,9,1,1,NaN,NaN,2500,9,10,2,2,3,NaN,1.0,35.4,155.0,50.0,NaN,6.0,1
2,38.0,1,1,1,NaN,NaN,2815,7,10,1,1,2,3.0,2.0,36.4,166.0,71.0,NaN,6.0,1
3,36.0,1,1,1,NaN,NaN,2125,8,7,1,2,2,3.0,2.0,34.9,136.0,71.0,NaN,6.0,1
4,32.0,9,1,1,NaN,NaN,2115,9,10,2,2,2,3.0,3.0,36.1,131.0,72.0,NaN,6.0,1
5,36.0,1,1,1,NaN,NaN,2160,5,0,1,2,3,NaN,1.0,34.0,132.0,49.0,17.0,6.0,1
6,40.0,1,1,2,1.0,5.0,2085,9,10,2,2,2,3.0,2.0,35.0,136.0,96.0,NaN,6.0,1
7,38.0,1,1,1,NaN,NaN,2985,7,10,2,2,3,NaN,1.0,35.0,100.0,66.0,NaN,6.0,1
8,33.0,1,4,2,1.0,6.0,1660,9,10,2,2,2,3.0,2.0,36.7,158.0,53.0,NaN,6.0,1
9,40.0,9,1,1,NaN,NaN,2700,9,10,2,2,3,NaN,1.0,33.0,128.0,92.0,NaN,6.0,1
10,40.0,1,1,1,NaN,NaN,4070,9,10,2,2,3,NaN,1.0,36.4,146.0,86.0,NaN,6.0,1
11,40.0,1,1,2,1.0,3.0,4300,7,10,1,2,3,NaN,1.0,NaN,NaN,NaN,NaN,6.0,1
12,40.0,1,1,1,NaN,NaN,1950,7,10,2,2,2,3.0,2.0,NaN,139.0,52.0,NaN,6.0,1
13,36.0,1,1,2,2.0,3.0,2700,8,10,2,2,3,NaN,1.0,35.2,140.0,60.0,0.0,6.0,1
14,40.0,1,3,2,1.0,NaN,3335,5,8,1,2,2,3.0,2.0,35.0,139.0,37.0,NaN,5.0,1
15,38.0,2,3,2,1.0,2.0,2890,5,8,1,2,3,NaN,1.0,35.0,152.0,52.0,4.0,5.0,1
16,35.0,1,2,2,1.0,6.0,1930,7,10,1,2,2,3.0,2.0,35.4,152.0,37.0,NaN,5.0,1
17,36.0,1,3,1,NaN,NaN,3300,8,10,2,2,3,NaN,1.0,35.0,100.0,12.0,9.0,5.0,1
18,40.0,1,2,2,1.0,5.0,3400,8,10,2,1,2,3.0,2.0,NaN,145.0,55.0,NaN,5.0,1
19,40.0,1,3,2,1.0,3.0,3010,5,10,1,2,2,3.0,2.0,34.6,145.0,92.0,8.0,5.0,1
20,40.0,1,2,1,NaN,NaN,3000,7,10,1,2,3,NaN,1.0,36.5,132.0,90.0,NaN,5.0,1
21,NaN,1,3,1,NaN,NaN,3200,6,10,1,2,3,NaN,1.0,35.0,100.0,69.0,4.0,5.0,1
22,40.0,1,3,2,1.0,5.0,2430,6,10,1,2,3,NaN,1.0,33.6,133.0,40.0,6.0,5.0,1
23,36.0,1,3,2,1.0,1.0,3200,5,10,1,2,2,3.0,2.0,36.0,105.0,92.0,NaN,5.0,1
24,39.0,1,3,2,1.0,4.0,2900,6,10,1,2,3,NaN,1.0,36.0,132.0,64.0,NaN,5.0,1
25,40.0,1,2,2,1.0,3.0,2600,7,10,1,2,3,NaN,1.0,34.9,148.0,88.0,9.0,5.0,1
26,40.0,1,3,1,NaN,NaN,2500,6,8,2,2,2,3.0,3.0,36.4,161.0,78.0,7.0,5.0,1
27,30.0,1,1,3,NaN,NaN,1165,4,5,2,2,2,3.0,2.0,33.0,148.0,50.0,NaN,3.0,1
28,41.0,1,2,2,1.0,2.0,3420,3,5,1,2,3,NaN,1.0,35.0,158.0,79.0,18.0,3.0,1
29,40.0,1,3,1,NaN,NaN,2775,5,6,1,2,3,NaN,1.0,34.0,165.0,78.0,13.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,40.0,9,3,2,1.0,6.0,4250,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
642,NaN,9,3,1,NaN,NaN,3000,7,9,1,2,1,NaN,NaN,34.9,180.0,73.0,NaN,NaN,0
643,38.0,9,3,1,NaN,NaN,2450,7,10,2,2,1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0
644,40.0,9,1,2,1.0,5.0,2150,7,9,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
645,NaN,9,1,1,NaN,NaN,2550,2,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
646,37.0,9,1,1,NaN,NaN,3440,7,9,1,2,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
647,40.0,9,1,2,1.0,3.0,2390,6,9,1,2,2,1.0,NaN,34.0,141.0,83.0,NaN,NaN,0
648,38.0,9,4,2,1.0,6.0,2670,4,6,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
649,39.0,9,2,1,NaN,NaN,3000,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
650,34.0,1,1,1,NaN,NaN,2135,9,10,2,1,2,NaN,NaN,35.4,170.0,66.0,NaN,NaN,0
651,32.0,1,1,1,NaN,NaN,2165,9,10,2,1,2,NaN,NaN,35.7,168.0,56.0,NaN,NaN,0
652,40.0,2,3,2,1.0,2.0,2870,9,10,2,1,2,NaN,NaN,NaN,126.0,90.0,NaN,NaN,0
653,40.0,2,1,1,NaN,NaN,2300,9,10,2,1,2,NaN,NaN,35.0,135.0,82.0,NaN,NaN,0
654,39.0,2,1,2,1.0,2.0,2890,8,10,2,1,2,NaN,NaN,NaN,124.0,75.0,NaN,NaN,0
655,40.0,1,3,1,NaN,NaN,3295,4,7,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
656,36.0,1,3,2,1.0,2.0,3500,7,10,1,1,2,NaN,NaN,36.6,NaN,92.0,NaN,NaN,0
657,36.0,1,3,1,NaN,NaN,2340,9,10,2,1,2,NaN,NaN,NaN,136.0,95.0,NaN,NaN,0
658,40.0,1,3,1,NaN,NaN,3400,8,10,2,1,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0
659,NaN,1,1,2,1.0,5.0,1640,9,10,2,1,2,NaN,NaN,36.2,92.0,96.0,NaN,NaN,0
660,NaN,1,1,2,1.0,5.0,2160,8,10,2,1,2,NaN,NaN,34.1,105.0,91.0,NaN,NaN,0
661,39.0,1,1,1,NaN,NaN,2800,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
662,37.0,1,1,1,NaN,NaN,2700,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
663,36.0,1,1,1,NaN,NaN,3300,9,10,2,1,2,NaN,NaN,37.3,137.0,72.0,NaN,NaN,0
664,40.0,1,1,2,1.0,1.0,3200,9,10,2,1,2,NaN,NaN,34.0,157.0,94.0,NaN,NaN,0
665,38.0,1,1,1,NaN,NaN,3650,9,10,2,1,2,NaN,NaN,36.0,144.0,83.0,NaN,NaN,0
666,40.0,1,2,1,NaN,NaN,3500,5,8,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
667,40.0,1,2,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,34.9,164.0,98.0,NaN,NaN,0
668,40.0,1,2,1,NaN,NaN,3370,7,9,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
669,40.0,9,1,1,NaN,NaN,3400,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
670,NaN,9,1,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,33.0,124.0,92.0,NaN,NaN,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 671 entries, 0 to 670
Data columns (total 20 columns):
GA                   599 non-null float64
FHR_during_labour    671 non-null int64
Amniotic_fluid       671 non-null int64
Delivery_Mode        671 non-null int64
CS_category          262 non-null float64
CS_indication        261 non-null float64
BW                   671 non-null int64
Apgar_1min           671 non-null int64
Apgar_5min           671 non-null int64
BMV                  671 non-null int64
Outcome_30min        671 non-null int64
Outcome_24hours      671 non-null int64
Outcome_7days        410 non-null float64
Time_of_death        124 non-null float64
temp12ad0            377 non-null float64
puls13ad0            363 non-null float64
oxy14ad0             371 non-null float64
HIE_highest          154 non-null float64
major_cause          124 non-null float64
outcome              671 non-null int64
dtypes: float64(10), int64(10)
memory usage: 104.9 KB

In [7]:
df = df.replace('\t','',regex=True)
df = df.replace(' ','',regex=True)
df = df.replace('\?','np.nan',regex=True)

## Data Cleaning

In [8]:
# Remove rows where taget are missing
missing_row = df['outcome'].isnull()
print('Number of rows where target are missing:')
print(sum(missing_row))

df = df[~missing_row]
df

Number of rows where target are missing:
0

,GA,FHR_during_labour,Amniotic_fluid,Delivery_Mode,CS_category,CS_indication,BW,Apgar_1min,Apgar_5min,BMV,Outcome_30min,Outcome_24hours,Outcome_7days,Time_of_death,temp12ad0,puls13ad0,oxy14ad0,HIE_highest,major_cause,outcome
0,42.0,1,2,1,NaN,NaN,3000,8,10,2,2,2,3.0,2.0,36.0,144.0,60.0,NaN,6.0,1
1,40.0,9,1,1,NaN,NaN,2500,9,10,2,2,3,NaN,1.0,35.4,155.0,50.0,NaN,6.0,1
2,38.0,1,1,1,NaN,NaN,2815,7,10,1,1,2,3.0,2.0,36.4,166.0,71.0,NaN,6.0,1
3,36.0,1,1,1,NaN,NaN,2125,8,7,1,2,2,3.0,2.0,34.9,136.0,71.0,NaN,6.0,1
4,32.0,9,1,1,NaN,NaN,2115,9,10,2,2,2,3.0,3.0,36.1,131.0,72.0,NaN,6.0,1
5,36.0,1,1,1,NaN,NaN,2160,5,0,1,2,3,NaN,1.0,34.0,132.0,49.0,17.0,6.0,1
6,40.0,1,1,2,1.0,5.0,2085,9,10,2,2,2,3.0,2.0,35.0,136.0,96.0,NaN,6.0,1
7,38.0,1,1,1,NaN,NaN,2985,7,10,2,2,3,NaN,1.0,35.0,100.0,66.0,NaN,6.0,1
8,33.0,1,4,2,1.0,6.0,1660,9,10,2,2,2,3.0,2.0,36.7,158.0,53.0,NaN,6.0,1
9,40.0,9,1,1,NaN,NaN,2700,9,10,2,2,3,NaN,1.0,33.0,128.0,92.0,NaN,6.0,1
10,40.0,1,1,1,NaN,NaN,4070,9,10,2,2,3,NaN,1.0,36.4,146.0,86.0,NaN,6.0,1
11,40.0,1,1,2,1.0,3.0,4300,7,10,1,2,3,NaN,1.0,NaN,NaN,NaN,NaN,6.0,1
12,40.0,1,1,1,NaN,NaN,1950,7,10,2,2,2,3.0,2.0,NaN,139.0,52.0,NaN,6.0,1
13,36.0,1,1,2,2.0,3.0,2700,8,10,2,2,3,NaN,1.0,35.2,140.0,60.0,0.0,6.0,1
14,40.0,1,3,2,1.0,NaN,3335,5,8,1,2,2,3.0,2.0,35.0,139.0,37.0,NaN,5.0,1
15,38.0,2,3,2,1.0,2.0,2890,5,8,1,2,3,NaN,1.0,35.0,152.0,52.0,4.0,5.0,1
16,35.0,1,2,2,1.0,6.0,1930,7,10,1,2,2,3.0,2.0,35.4,152.0,37.0,NaN,5.0,1
17,36.0,1,3,1,NaN,NaN,3300,8,10,2,2,3,NaN,1.0,35.0,100.0,12.0,9.0,5.0,1
18,40.0,1,2,2,1.0,5.0,3400,8,10,2,1,2,3.0,2.0,NaN,145.0,55.0,NaN,5.0,1
19,40.0,1,3,2,1.0,3.0,3010,5,10,1,2,2,3.0,2.0,34.6,145.0,92.0,8.0,5.0,1
20,40.0,1,2,1,NaN,NaN,3000,7,10,1,2,3,NaN,1.0,36.5,132.0,90.0,NaN,5.0,1
21,NaN,1,3,1,NaN,NaN,3200,6,10,1,2,3,NaN,1.0,35.0,100.0,69.0,4.0,5.0,1
22,40.0,1,3,2,1.0,5.0,2430,6,10,1,2,3,NaN,1.0,33.6,133.0,40.0,6.0,5.0,1
23,36.0,1,3,2,1.0,1.0,3200,5,10,1,2,2,3.0,2.0,36.0,105.0,92.0,NaN,5.0,1
24,39.0,1,3,2,1.0,4.0,2900,6,10,1,2,3,NaN,1.0,36.0,132.0,64.0,NaN,5.0,1
25,40.0,1,2,2,1.0,3.0,2600,7,10,1,2,3,NaN,1.0,34.9,148.0,88.0,9.0,5.0,1
26,40.0,1,3,1,NaN,NaN,2500,6,8,2,2,2,3.0,3.0,36.4,161.0,78.0,7.0,5.0,1
27,30.0,1,1,3,NaN,NaN,1165,4,5,2,2,2,3.0,2.0,33.0,148.0,50.0,NaN,3.0,1
28,41.0,1,2,2,1.0,2.0,3420,3,5,1,2,3,NaN,1.0,35.0,158.0,79.0,18.0,3.0,1
29,40.0,1,3,1,NaN,NaN,2775,5,6,1,2,3,NaN,1.0,34.0,165.0,78.0,13.0,3.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
641,40.0,9,3,2,1.0,6.0,4250,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
642,NaN,9,3,1,NaN,NaN,3000,7,9,1,2,1,NaN,NaN,34.9,180.0,73.0,NaN,NaN,0
643,38.0,9,3,1,NaN,NaN,2450,7,10,2,2,1,NaN,NaN,NaN,NaN,NaN,0.0,NaN,0
644,40.0,9,1,2,1.0,5.0,2150,7,9,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
645,NaN,9,1,1,NaN,NaN,2550,2,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
646,37.0,9,1,1,NaN,NaN,3440,7,9,1,2,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,0
647,40.0,9,1,2,1.0,3.0,2390,6,9,1,2,2,1.0,NaN,34.0,141.0,83.0,NaN,NaN,0
648,38.0,9,4,2,1.0,6.0,2670,4,6,1,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
649,39.0,9,2,1,NaN,NaN,3000,7,10,1,2,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
650,34.0,1,1,1,NaN,NaN,2135,9,10,2,1,2,NaN,NaN,35.4,170.0,66.0,NaN,NaN,0
651,32.0,1,1,1,NaN,NaN,2165,9,10,2,1,2,NaN,NaN,35.7,168.0,56.0,NaN,NaN,0
652,40.0,2,3,2,1.0,2.0,2870,9,10,2,1,2,NaN,NaN,NaN,126.0,90.0,NaN,NaN,0
653,40.0,2,1,1,NaN,NaN,2300,9,10,2,1,2,NaN,NaN,35.0,135.0,82.0,NaN,NaN,0
654,39.0,2,1,2,1.0,2.0,2890,8,10,2,1,2,NaN,NaN,NaN,124.0,75.0,NaN,NaN,0
655,40.0,1,3,1,NaN,NaN,3295,4,7,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
656,36.0,1,3,2,1.0,2.0,3500,7,10,1,1,2,NaN,NaN,36.6,NaN,92.0,NaN,NaN,0
657,36.0,1,3,1,NaN,NaN,2340,9,10,2,1,2,NaN,NaN,NaN,136.0,95.0,NaN,NaN,0
658,40.0,1,3,1,NaN,NaN,3400,8,10,2,1,2,NaN,NaN,NaN,NaN,NaN,2.0,NaN,0
659,NaN,1,1,2,1.0,5.0,1640,9,10,2,1,2,NaN,NaN,36.2,92.0,96.0,NaN,NaN,0
660,NaN,1,1,2,1.0,5.0,2160,8,10,2,1,2,NaN,NaN,34.1,105.0,91.0,NaN,NaN,0
661,39.0,1,1,1,NaN,NaN,2800,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
662,37.0,1,1,1,NaN,NaN,2700,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
663,36.0,1,1,1,NaN,NaN,3300,9,10,2,1,2,NaN,NaN,37.3,137.0,72.0,NaN,NaN,0
664,40.0,1,1,2,1.0,1.0,3200,9,10,2,1,2,NaN,NaN,34.0,157.0,94.0,NaN,NaN,0
665,38.0,1,1,1,NaN,NaN,3650,9,10,2,1,2,NaN,NaN,36.0,144.0,83.0,NaN,NaN,0
666,40.0,1,2,1,NaN,NaN,3500,5,8,1,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
667,40.0,1,2,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,34.9,164.0,98.0,NaN,NaN,0
668,40.0,1,2,1,NaN,NaN,3370,7,9,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
669,40.0,9,1,1,NaN,NaN,3400,9,10,2,1,2,1.0,NaN,NaN,NaN,NaN,NaN,NaN,0
670,NaN,9,1,1,NaN,NaN,3500,9,10,2,1,2,NaN,NaN,33.0,124.0,92.0,NaN,NaN,0

We find bad rows which contain too many missing values, then remove them.

In [10]:
def remove_bad_rows(df,bad_row_threshold):   
    # find bad rows having too many missing values
    n_null = np.array(df.isnull().sum(axis=1))
    bad_row = np.array([]).astype(int)
    for t in range(len(n_null)):
        if n_null[t] >= bad_row_threshold:
            bad_row = np.append(bad_row,t)

    #print(bad_row)
    print('number of bad rows:',len(bad_row))

    # delete bad rows
    df = df.drop(bad_row)
    #df.info()
    return df

In [11]:
df = remove_bad_rows(df,4)
df.info()

number of bad rows: 517
<class 'pandas.core.frame.DataFrame'>
Int64Index: 154 entries, 0 to 647
Data columns (total 20 columns):
GA                   149 non-null float64
FHR_during_labour    154 non-null int64
Amniotic_fluid       154 non-null int64
Delivery_Mode        154 non-null int64
CS_category          115 non-null float64
CS_indication        114 non-null float64
BW                   154 non-null int64
Apgar_1min           154 non-null int64
Apgar_5min           154 non-null int64
BMV                  154 non-null int64
Outcome_30min        154 non-null int64
Outcome_24hours      154 non-null int64
Outcome_7days        111 non-null float64
Time_of_death        83 non-null float64
temp12ad0            148 non-null float64
puls13ad0            153 non-null float64
oxy14ad0             153 non-null float64
HIE_highest          77 non-null float64
major_cause          83 non-null float64
outcome              154 non-null int64
dtypes: float64(10), int64(10)
memory usage: 25.3 KB

We determine and drop the variables with excessive missing values from the dataset.

In [12]:
def remove_bad_columns(df,bad_column_threshold):
    # find bad columns having too many missing values
    n_null = np.array(df.isnull().sum(axis=0))
    bad_col = np.array([]).astype(int)
    for i in range(len(n_null)):
        if n_null[i] >= bad_column_threshold:
            bad_col = np.append(bad_col,i)

    #print(bad_col)
    print('number of bad columns:',len(bad_col))

    # delete bad columns
    df = df.drop(df.columns[bad_col],axis=1)
    #df.info()
    return df

In [13]:
df = remove_bad_columns(df,50)
df.info()

number of bad columns: 3
<class 'pandas.core.frame.DataFrame'>
Int64Index: 154 entries, 0 to 647
Data columns (total 17 columns):
GA                   149 non-null float64
FHR_during_labour    154 non-null int64
Amniotic_fluid       154 non-null int64
Delivery_Mode        154 non-null int64
CS_category          115 non-null float64
CS_indication        114 non-null float64
BW                   154 non-null int64
Apgar_1min           154 non-null int64
Apgar_5min           154 non-null int64
BMV                  154 non-null int64
Outcome_30min        154 non-null int64
Outcome_24hours      154 non-null int64
Outcome_7days        111 non-null float64
temp12ad0            148 non-null float64
puls13ad0            153 non-null float64
oxy14ad0             153 non-null float64
outcome              154 non-null int64
dtypes: float64(7), int64(10)
memory usage: 21.7 KB

For convenience, we separate independents `X` and dependent `y` from the data.

In [14]:
dfx = df.drop('outcome',axis=1)
dfy = df['outcome']

In [15]:
# number of uniques of each column (excluding NaN)
nu = np.array([len(pd.unique(dfx[col].dropna())) for col in dfx.columns])
print('number of uniques of each variable:')
print(nu)

number of uniques of each variable:
[ 15   3   4   3   2   6 107   9   9   2   2   3   3  41  66  52]

In [16]:
def define_variable_type(df,nu):
    i_binary = [] ; i_category = [] ; i_continuous = []
    for i in range(len(nu)):
        if nu[i] == 2: # binary 
            i_binary.append(i)
        elif nu[i] < 5: # !!!! NOTE: this is not always correct, depending on data
            i_category.append(i)
        else:
            i_continuous.append(i)

    print('i_binary:',i_binary)
    print('i_category:',i_category)   
    #i_binary, i_category, i_continuous
    
    variable_type  = np.ones(len(nu))  # binary
    variable_type[i_category] = 2   # categorical
    variable_type[i_continuous] = 3 # continuous

    return variable_type #,i_binary,i_category,i_continuous

In [17]:
variable_type = define_variable_type(dfx,nu)
print('variable type:',variable_type)

i_binary: [4, 9, 10]
i_category: [1, 2, 3, 11, 12]
variable type: [3. 2. 2. 2. 1. 3. 3. 3. 3. 1. 1. 2. 2. 3. 3. 3.]

In [18]:
def impute_missing(df,variable_type):
    # impute binary and categorical variables by the most frequency (in each column)
    # continuous variable by median
    # input: df: pandas data frame, variable_type: list
    # output: df2: pandas data frame
    df2 = df.copy()
    for i,col in enumerate(df.columns):
        if variable_type[i] < 3: # binary or caterogy
            df2[col] = df[col].fillna(df[col].mode().iloc[0])
        else: # continuous
            df2[col] = df[col].fillna(df[col].median())    
    return df2

In [19]:
dfx_imputed = impute_missing(dfx,variable_type)
dfx_imputed

,GA,FHR_during_labour,Amniotic_fluid,Delivery_Mode,CS_category,CS_indication,BW,Apgar_1min,Apgar_5min,BMV,Outcome_30min,Outcome_24hours,Outcome_7days,temp12ad0,puls13ad0,oxy14ad0
0,42.0,1,2,1,1.0,4.0,3000,8,10,2,2,2,3.0,36.00,144.0,60.0
2,38.0,1,1,1,1.0,4.0,2815,7,10,1,1,2,3.0,36.40,166.0,71.0
3,36.0,1,1,1,1.0,4.0,2125,8,7,1,2,2,3.0,34.90,136.0,71.0
4,32.0,9,1,1,1.0,4.0,2115,9,10,2,2,2,3.0,36.10,131.0,72.0
5,36.0,1,1,1,1.0,4.0,2160,5,0,1,2,3,3.0,34.00,132.0,49.0
6,40.0,1,1,2,1.0,5.0,2085,9,10,2,2,2,3.0,35.00,136.0,96.0
8,33.0,1,4,2,1.0,6.0,1660,9,10,2,2,2,3.0,36.70,158.0,53.0
13,36.0,1,1,2,2.0,3.0,2700,8,10,2,2,3,3.0,35.20,140.0,60.0
14,40.0,1,3,2,1.0,4.0,3335,5,8,1,2,2,3.0,35.00,139.0,37.0
15,38.0,2,3,2,1.0,2.0,2890,5,8,1,2,3,3.0,35.00,152.0,52.0
16,35.0,1,2,2,1.0,6.0,1930,7,10,1,2,2,3.0,35.40,152.0,37.0
17,36.0,1,3,1,1.0,4.0,3300,8,10,2,2,3,3.0,35.00,100.0,12.0
18,40.0,1,2,2,1.0,5.0,3400,8,10,2,1,2,3.0,35.05,145.0,55.0
19,40.0,1,3,2,1.0,3.0,3010,5,10,1,2,2,3.0,34.60,145.0,92.0
22,40.0,1,3,2,1.0,5.0,2430,6,10,1,2,3,3.0,33.60,133.0,40.0
23,36.0,1,3,2,1.0,1.0,3200,5,10,1,2,2,3.0,36.00,105.0,92.0
24,39.0,1,3,2,1.0,4.0,2900,6,10,1,2,3,3.0,36.00,132.0,64.0
25,40.0,1,2,2,1.0,3.0,2600,7,10,1,2,3,3.0,34.90,148.0,88.0
26,40.0,1,3,1,1.0,4.0,2500,6,8,2,2,2,3.0,36.40,161.0,78.0
27,30.0,1,1,3,1.0,4.0,1165,4,5,2,2,2,3.0,33.00,148.0,50.0
28,41.0,1,2,2,1.0,2.0,3420,3,5,1,2,3,3.0,35.00,158.0,79.0
29,40.0,1,3,1,1.0,4.0,2775,5,6,1,2,3,3.0,34.00,165.0,78.0
30,40.0,2,1,2,1.0,2.0,2545,4,6,1,2,3,3.0,35.90,170.0,94.0
31,42.0,1,1,1,1.0,4.0,3100,4,4,1,2,3,3.0,36.70,147.0,80.0
32,36.0,1,3,2,1.0,2.0,3000,7,6,1,2,2,3.0,37.80,202.0,93.0
33,37.0,2,2,2,1.0,2.0,2750,5,5,1,2,2,3.0,33.40,71.0,90.0
34,38.0,1,2,2,1.0,6.0,2500,3,4,1,2,2,3.0,34.50,142.0,92.0
35,40.0,1,1,2,1.0,6.0,1420,1,4,1,2,2,3.0,32.70,120.0,63.0
36,35.0,2,1,1,1.0,4.0,1770,3,10,2,2,2,3.0,35.00,120.0,88.0
37,33.0,2,2,2,1.0,3.0,1590,3,4,1,2,3,3.0,36.60,90.0,42.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
336,40.0,1,1,2,1.0,5.0,3050,3,5,1,2,2,1.0,34.80,116.0,95.0
338,40.0,1,3,2,1.0,4.0,3100,6,8,2,1,2,3.0,36.10,134.0,94.0
339,40.0,1,2,2,1.0,1.0,3900,8,10,2,1,2,3.0,36.30,115.0,84.0
344,35.0,1,4,2,1.0,5.0,2500,6,8,1,2,2,1.0,34.40,120.0,92.0
345,40.0,2,3,2,1.0,2.0,3120,7,10,1,2,1,3.0,36.00,136.0,96.0
346,41.0,2,3,2,1.0,2.0,2960,9,10,2,2,1,3.0,36.40,129.0,83.0
347,40.0,2,1,2,1.0,2.0,3290,6,8,1,2,2,1.0,34.50,136.0,92.0
348,37.0,2,1,2,1.0,2.0,3600,6,10,1,2,2,1.0,36.60,138.0,94.0
349,39.0,2,1,2,1.0,2.0,2650,9,10,2,2,2,2.0,34.00,176.0,80.0
351,40.0,2,2,2,1.0,5.0,3510,3,6,1,2,2,1.0,34.00,200.0,50.0
352,40.0,1,3,2,1.0,3.0,3030,8,10,1,2,2,1.0,35.05,134.0,87.0
357,40.0,1,3,2,1.0,5.0,3200,7,8,1,2,2,1.0,35.70,144.0,96.0
359,36.0,1,3,2,1.0,5.0,2930,8,10,2,2,1,3.0,36.50,162.0,93.0
361,36.0,1,3,2,1.0,1.0,2450,8,10,2,2,2,1.0,35.90,136.0,66.0
364,38.0,1,1,2,1.0,4.0,2380,5,10,1,2,1,3.0,36.00,132.0,96.0
367,40.0,1,1,2,1.0,1.0,2620,6,10,1,2,1,3.0,35.40,138.0,92.0
372,40.0,1,1,2,1.0,3.0,4000,6,9,1,2,2,1.0,35.00,133.0,55.0
373,40.0,1,1,2,1.0,3.0,3400,8,10,2,2,1,3.0,36.00,140.0,95.0
383,40.0,9,2,2,1.0,5.0,3100,4,10,1,2,1,3.0,37.10,134.0,98.0
399,34.0,1,1,2,1.0,5.0,1850,7,10,1,2,2,1.0,35.00,181.0,85.0
407,35.0,1,1,2,1.0,4.0,1810,7,8,1,2,2,1.0,36.00,144.0,96.0
422,32.0,1,1,2,1.0,5.0,1230,8,10,2,2,2,2.0,35.00,144.0,60.0
423,32.0,1,1,2,1.0,5.0,1320,7,10,2,2,2,2.0,35.20,63.0,43.0
495,38.0,2,1,2,1.0,2.0,2610,5,7,1,2,2,1.0,33.80,140.0,90.0
496,36.0,2,1,2,1.0,2.0,2630,3,7,1,2,2,1.0,35.80,130.0,87.0
498,36.0,2,1,2,1.0,4.0,1860,8,10,2,2,2,1.0,35.50,141.0,98.0
502,36.0,2,1,2,1.0,2.0,3100,9,10,2,2,2,1.0,36.00,138.0,77.0
523,39.0,1,3,2,1.0,3.0,2420,9,10,2,2,2,1.0,35.00,186.0,88.0
546,37.0,1,1,2,1.0,3.0,3200,7,9,1,2,1,3.0,35.10,112.0,89.0
647,40.0,9,1,2,1.0,3.0,2390,6,9,1,2,2,1.0,34.00,141.0,83.0

In [20]:
dfx_imputed.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 154 entries, 0 to 647
Data columns (total 16 columns):
GA                   154 non-null float64
FHR_during_labour    154 non-null int64
Amniotic_fluid       154 non-null int64
Delivery_Mode        154 non-null int64
CS_category          154 non-null float64
CS_indication        154 non-null float64
BW                   154 non-null int64
Apgar_1min           154 non-null int64
Apgar_5min           154 non-null int64
BMV                  154 non-null int64
Outcome_30min        154 non-null int64
Outcome_24hours      154 non-null int64
Outcome_7days        154 non-null float64
temp12ad0            154 non-null float64
puls13ad0            154 non-null float64
oxy14ad0             154 non-null float64
dtypes: float64(7), int64(9)
memory usage: 20.5 KB

## Data Processing

### Attributes

In [21]:
def convert_binary_and_category(x,variable_type):
    """
    convert binary to +-1, category to one hot; remain continuous.
    """
    
    onehot_encoder = OneHotEncoder(sparse=False,categories='auto')

    # create 2 initial columns
    x_new = np.zeros((x.shape[0],2))

    for i,i_type in enumerate(variable_type):
        if i_type == 1: # binary
            unique_value = np.unique(x[:,i])
            x1 = np.array([-1. if value == unique_value[0] else 1. for value in x[:,i]])        
            x_new = np.hstack((x_new,x1[:,np.newaxis]))

        elif i_type == 2: # category
            x1 = onehot_encoder.fit_transform(x[:,i].reshape(-1,1))
            x_new = np.hstack((x_new,x1))
            
        else: # continuous      
            x_new = np.hstack((x_new,x[:,i][:,np.newaxis]))      

    # drop the 2 initial column
    x_new = x_new[:,2:]
    
    return x_new.astype(float)

In [22]:
# convert x
x = np.array(dfx_imputed)
x_new = convert_binary_and_category(x,variable_type)

print(x_new.shape)
print(x_new)

(154, 27)
[[ 42.    1.    0.  ...  36.  144.   60. ]
 [ 38.    1.    0.  ...  36.4 166.   71. ]
 [ 36.    1.    0.  ...  34.9 136.   71. ]
 ...
 [ 39.    1.    0.  ...  35.  186.   88. ]
 [ 37.    1.    0.  ...  35.1 112.   89. ]
 [ 40.    0.    0.  ...  34.  141.   83. ]]

### Target

In [23]:
y = np.array(dfy)
print(np.unique(y,return_counts=True))

# if target is already 0 and 1
y_new = y #and delete lines below convert  
print(np.unique(y_new,return_counts=True))

(array([0, 1]), array([71, 83]))
(array([0, 1]), array([71, 83]))

In [24]:
# combine X and y and save to a file
xy_new = np.hstack((x_new,y_new[:,np.newaxis]))
np.savetxt('tanzania_processed.dat',xy_new,fmt='%f')